/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackage;

import DAO.LoanDAO;
import data.Cal;
import data.LoanDetails;
import data.Validation;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sanke
 */
public class AddLoan extends javax.swing.JFrame {

    /**
     * Creates new form AddLoan
     */
    public static int loanIDToUpdate = -1;

    public AddLoan(int loandID) {
        loanIDToUpdate = loandID;
        initComponents();

        System.out.println(loanIDToUpdate);
        if (loanIDToUpdate >= 0) {
            btnadd.setText("Update");
            LoanDAO dao1 = new LoanDAO();
            Vector<Vector<String>> dataset = new Vector<Vector<String>>();
            dataset = dao1.getLoanFromID(loanIDToUpdate);
            Vector<String> loanData = dataset.get(0);
            txtAmo.setText(loanData.get(1));
            TxtDura.setText(loanData.get(3));
            txtdiscript.setText(loanData.get(4));
            txtIntr.setText(loanData.get(5));
            txtAccno.setText(loanData.get(6));
            txtFinanceName.setText(loanData.get(7));
            txtbranch.setText(loanData.get(8));
            txtNoIns.setText(loanData.get(11));
            txtMinIns.setText(loanData.get(12));
            java.util.Date date;
            try {
                date = new SimpleDateFormat("yyyy-MM-dd").parse(loanData.get(2));
                dchapproved.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(Profit.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            btnadd.setText("Add");
        }

    }

    private void clear() {
        TxtDura.setText("");
        txtAccno.setText("");
        txtAmo.setText("");
        txtFinanceName.setText("");
        txtIntr.setText("");
        txtMinIns.setText("");
        txtNoIns.setText("");
        txtbranch.setText("");
        txtbranch.setText("");
        txtdiscript.setText("");
        lblEAccno.setText(" ");
        lblEBranchName.setText(" ");
        lblEMinIns.setText(" ");
        lblEamt.setText(" ");
        lblEdate.setText(" ");
        lblEdur.setText(" ");
        lblEfinName.setText(" ");
        lblEintrate.setText(" ");
        lblEnoIns.setText(" ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMinIns = new javax.swing.JTextField();
        txtNoIns = new javax.swing.JTextField();
        TxtDura = new javax.swing.JTextField();
        txtIntr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAmo = new javax.swing.JTextField();
        lblEamt = new javax.swing.JLabel();
        lblEdur = new javax.swing.JLabel();
        lblEintrate = new javax.swing.JLabel();
        lblEnoIns = new javax.swing.JLabel();
        lblEMinIns = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAccno = new javax.swing.JTextField();
        txtFinanceName = new javax.swing.JTextField();
        txtbranch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiscript = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        lblEAccno = new javax.swing.JLabel();
        lblEBranchName = new javax.swing.JLabel();
        lblEfinName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dchapproved = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        lblEdate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        jLabel6.setText("Min Amount of Installement");

        jLabel3.setText("Duration To Pay");

        jLabel4.setText("Intrest Rate");

        jLabel5.setText("No of Installments");

        txtMinIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinInsActionPerformed(evt);
            }
        });

        txtNoIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoInsActionPerformed(evt);
            }
        });

        TxtDura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDuraActionPerformed(evt);
            }
        });

        txtIntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntrActionPerformed(evt);
            }
        });

        jLabel2.setText("Amount");

        txtAmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmoActionPerformed(evt);
            }
        });

        lblEamt.setForeground(new java.awt.Color(255, 0, 0));
        lblEamt.setText(" ");

        lblEdur.setForeground(new java.awt.Color(255, 0, 0));
        lblEdur.setText(" ");

        lblEintrate.setForeground(new java.awt.Color(255, 0, 0));
        lblEintrate.setText(" ");

        lblEnoIns.setForeground(new java.awt.Color(255, 0, 0));
        lblEnoIns.setText(" ");

        lblEMinIns.setForeground(new java.awt.Color(255, 0, 0));
        lblEMinIns.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEdur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoIns)
                    .addComponent(txtIntr)
                    .addComponent(TxtDura)
                    .addComponent(txtAmo)
                    .addComponent(txtMinIns, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblEamt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEintrate, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblEnoIns, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblEMinIns, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEamt)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblEdur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEintrate)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNoIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnoIns)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMinIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEMinIns)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Name Of the Financial Institue");

        txtAccno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccnoActionPerformed(evt);
            }
        });

        txtFinanceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinanceNameActionPerformed(evt);
            }
        });

        txtbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbranchActionPerformed(evt);
            }
        });

        jLabel7.setText("Branch Name");

        jLabel8.setText("Account No");

        txtdiscript.setColumns(20);
        txtdiscript.setRows(5);
        jScrollPane1.setViewportView(txtdiscript);

        jLabel9.setText("Discription");

        lblEAccno.setForeground(new java.awt.Color(255, 0, 0));
        lblEAccno.setText(" ");

        lblEBranchName.setForeground(new java.awt.Color(255, 0, 0));
        lblEBranchName.setText(" ");

        lblEfinName.setForeground(new java.awt.Color(255, 0, 0));
        lblEfinName.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEBranchName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFinanceName)
                    .addComponent(txtbranch)
                    .addComponent(txtAccno)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(lblEAccno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEfinName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtFinanceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEfinName)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEBranchName)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEAccno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setText("Date Approved");

        lblEdate.setForeground(new java.awt.Color(255, 0, 0));
        lblEdate.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchapproved, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dchapproved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdate)
                .addContainerGap())
        );

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnadd)
                    .addComponent(jButton3))
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950, 450));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccnoActionPerformed

    private void txtbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbranchActionPerformed

    private void txtMinInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinInsActionPerformed

    private void txtNoInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoInsActionPerformed

    private void txtIntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntrActionPerformed

    private void TxtDuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDuraActionPerformed

    private void txtFinanceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinanceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinanceNameActionPerformed

    private void txtAmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Profit pf1 = new Profit();
        pf1.General.setSelectedIndex(1);
        pf1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        //validations begin
        boolean b1 = true;
        String date1 = "";
        Cal cl1 = new Cal();
        Validation val1 = new Validation();
        try {
            date1 = dchapproved.getDate().toString();
            date1 = cl1.formatedDate(date1);
        } catch (NullPointerException ex) {
            lblEdate.setText("Please Fill");
            b1 = false;
        }
        if ((!val1.isNumeric(txtAmo.getText())) || (txtAmo.getText().equals(""))) {
            lblEamt.setText("Invalid");
            b1 = false;
        }
        if (!val1.isNumeric(TxtDura.getText()) || (txtAmo.getText().equals(""))) {
            lblEdur.setText("Invalid");
            b1 = false;
        }
        if (!val1.isNumeric(txtIntr.getText()) || (txtAmo.getText().equals(""))) {
            lblEintrate.setText("Invalid");
            b1 = false;
        }
        if (!val1.isNumeric(txtNoIns.getText()) || (txtAmo.getText().equals(""))) {
            lblEnoIns.setText("Invalid");
            b1 = false;
        }
        if (!val1.isNumeric(txtMinIns.getText()) || (txtAmo.getText().equals(""))) {
            lblEMinIns.setText("Invalid");
            b1 = false;
        }
        if (!val1.isNumeric(txtAmo.getText()) || (txtAmo.getText().equals(""))) {
            lblEnoIns.setText("Invalid");
            b1 = false;
        }
        if (txtFinanceName.getText().equals("")) {
            lblEfinName.setText("Invalid");
            b1 = false;
        }
        if (txtbranch.getText().equals("")) {
            lblEfinName.setText("Invalid");
            b1 = false;
        }
        if (!val1.isNumeric(txtAccno.getText()) || txtAccno.getText().equals("")) {
            lblEBranchName.setText("Invalid");
            b1 = false;
        }
        if (txtAccno.getText().equals("")) {
            lblEAccno.setText("Invalid");
            b1 = false;
        }
        if (b1) {
            LoanDAO dao1 = new LoanDAO();
            LoanDAO dao2 = new LoanDAO();
            LoanDetails dt1 = new LoanDetails(Double.parseDouble(txtAmo.getText()), date1, TxtDura.getText(),
                    txtdiscript.getText(), Double.parseDouble(txtIntr.getText()), Integer.parseInt(txtAccno.getText()),
                    txtFinanceName.getText(), txtbranch.getText());
            boolean b12 = false;
            if (loanIDToUpdate < 0) {

                b12 = dao1.addTrans(dt1);
                if (b12) {

                    clear();
                    JOptionPane.showMessageDialog(rootPane, "Successfully Added");
                    Profit pf1 = new Profit();
                    pf1.General.setSelectedIndex(1);
                    pf1.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Failed ");
                }

            } else {

                LoanDetails dt2 = new LoanDetails(Double.parseDouble(txtAmo.getText()), date1, TxtDura.getText(),
                        txtdiscript.getText(), Double.parseDouble(txtIntr.getText()), Integer.parseInt(txtAccno.getText()),
                        txtFinanceName.getText(), txtbranch.getText());
                dt2.setNO_of_ins(Integer.parseInt(txtNoIns.getText()));
                System.out.println(txtNoIns.getText() + "a");
                dt2.setMin_ins(Integer.parseInt(txtMinIns.getText()));
                dt2.setID(loanIDToUpdate);

                b12 = dao1.updateLoan(dt2);
                if (b12) {

                    clear();
                    JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
                    Profit pf1 = new Profit();
                    pf1.General.setSelectedIndex(1);
                    pf1.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Failed ");
                }

            }
        }


    }//GEN-LAST:event_btnaddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a =JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if(a == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLoan(loanIDToUpdate).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDura;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnadd;
    private com.toedter.calendar.JDateChooser dchapproved;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEAccno;
    private javax.swing.JLabel lblEBranchName;
    private javax.swing.JLabel lblEMinIns;
    private javax.swing.JLabel lblEamt;
    private javax.swing.JLabel lblEdate;
    private javax.swing.JLabel lblEdur;
    private javax.swing.JLabel lblEfinName;
    private javax.swing.JLabel lblEintrate;
    private javax.swing.JLabel lblEnoIns;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JTextField txtAccno;
    private javax.swing.JTextField txtAmo;
    private javax.swing.JTextField txtFinanceName;
    private javax.swing.JTextField txtIntr;
    private javax.swing.JTextField txtMinIns;
    private javax.swing.JTextField txtNoIns;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JTextArea txtdiscript;
    // End of variables declaration//GEN-END:variables
}
