/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appPackage;

import DAO.EmpDAO;
import data.Cal;
import data.Emp;
import data.ReportView;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Dell
 */
public class AllocateEmployee extends javax.swing.JFrame {
    private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header; //Used to store data header
    boolean isClicked = false;
    String tbl = "";
    
    /**
     * Creates new form AllocateEmployee
     */
    public AllocateEmployee() {
        initComponents();
        header = new Vector<String>();
        header.add("Emp ID");
        header.add("First Name");
        header.add("Last Name");
       // pnlBtn4.setBackground(new Color(0, 0, 0, 0));
        btnExit.setBackground(new Color(0, 0, 0, 0));
        home4.setBackground(new Color(0, 0, 0, 0));
        logout.setBackground(new Color(0, 0, 0, 0));
        loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("preprocess", jScrollPane6, tblPreProcess);
        
//        Cal c = new Cal();
//            c.setDateTime(lbldate, lbltime);
    }

            private void loadTable(String st, JScrollPane js, JTable jt) {

        EmpDAO dao = new EmpDAO();
        data = dao.getEmpAllocateDetails(st);

        jt.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        js.setViewportView(jt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGrind = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPacking = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLoading = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPreProcess = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        dch1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        home4 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDrag.setText("    ");
        getContentPane().add(lblDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 114, -1));

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });
        jScrollPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseMoved(evt);
            }
        });

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        tblEmp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblEmpMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });
        jScrollPane2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseMoved(evt);
            }
        });

        tblGrind.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGrind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGrindMouseClicked(evt);
            }
        });
        tblGrind.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblGrindMouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(tblGrind);

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });
        jScrollPane3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseMoved(evt);
            }
        });

        tblPacking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPackingMouseClicked(evt);
            }
        });
        tblPacking.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblPackingMouseMoved(evt);
            }
        });
        jScrollPane3.setViewportView(tblPacking);

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });
        jScrollPane4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseMoved(evt);
            }
        });

        tblLoading.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoading.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoadingMouseClicked(evt);
            }
        });
        tblLoading.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblLoadingMouseMoved(evt);
            }
        });
        jScrollPane4.setViewportView(tblLoading);

        jLabel2.setText("Grind");

        jLabel3.setText("Packing");

        jLabel4.setText("loading");

        jLabel5.setText("PreProcess");

        jScrollPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseClicked(evt);
            }
        });
        jScrollPane6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseMoved(evt);
            }
        });

        tblPreProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPreProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPreProcessMouseClicked(evt);
            }
        });
        tblPreProcess.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblPreProcessMouseMoved(evt);
            }
        });
        jScrollPane6.setViewportView(tblPreProcess);

        jLabel26.setText("View Allocated Emps");

        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(dch1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(dch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 145, 910, 440));

        home4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home4.setOpaque(false);
        home4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home4ActionPerformed(evt);
            }
        });
        getContentPane().add(home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home4ActionPerformed
//        int a =JOptionPane.showConfirmDialog(rootPane, "Do you want to got Home");
//        if(a == JOptionPane.YES_OPTION)
//        {
//            MainMenu m1 = new MainMenu();
//            m1.setVisible(true);
//            this.dispose();
//        }
        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home4ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a =JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if(a == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked

        
        int r = tblEmp.getSelectedRow();
        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(!isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-600);
            lblDrag.setText(tblEmp.getValueAt(r, 1).toString());
            isClicked=true;
            tbl = "emp";
        }
        else
        {
            
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            
                d.setSection("n/a");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("loading", jScrollPane6, tblPreProcess);
            
        }
        
        System.out.println(isClicked);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmpMouseClicked

    private void tblEmpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmpMouseMoved

    private void jScrollPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseMoved

        
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void tblGrindMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGrindMouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGrindMouseMoved

    private void tblPackingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPackingMouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPackingMouseMoved

    private void jScrollPane4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseMoved

    private void tblLoadingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoadingMouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLoadingMouseMoved

    private void jScrollPane2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseMoved

    private void jScrollPane3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseMoved

    private void tblGrindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGrindMouseClicked

        if(isClicked)
        {
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("grinding");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("loading", jScrollPane6, tblPreProcess);
            
        }
        
        else
        {
            int r = tblGrind.getSelectedRow();
            Point wp = this.getLocation();
            PointerInfo inf = MouseInfo.getPointerInfo();
            Point mp = inf.getLocation();
            lblDrag.setLocation(mp.x-215,mp.y-60);
            lblDrag.setText(tblGrind.getValueAt(r, 1).toString());
            isClicked=true;
            tbl = "gr";
        }
        
        System.out.println(isClicked);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGrindMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

        if(isClicked)
        {
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("grinding");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("loading", jScrollPane6, tblPreProcess);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

        System.out.println("aaaaaaaaaa");
        if(isClicked)
        {
            
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("n/a");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
        loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("loading", jScrollPane6, tblPreProcess);
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblPackingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPackingMouseClicked
     
        if(isClicked)
        {
            
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("packing");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("loading", jScrollPane6, tblPreProcess);
            
        }
        
        else
        {
            int r = tblPacking.getSelectedRow();
            Point wp = this.getLocation();
            PointerInfo inf = MouseInfo.getPointerInfo();
            Point mp = inf.getLocation();
            lblDrag.setLocation(mp.x-215,mp.y-60);
            lblDrag.setText(tblPacking.getValueAt(r, 1).toString());
            isClicked=true;
            tbl = "pk";
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPackingMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
   

        if(isClicked)
        {
            
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("packing");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("loading", jScrollPane6, tblPreProcess);
            
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved

    private void tblLoadingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoadingMouseClicked

        if(isClicked)
        {
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("loading");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("preprocess", jScrollPane6, tblPreProcess);
            
        }
        
        else
        {
            int r = tblLoading.getSelectedRow();
            Point wp = this.getLocation();
            PointerInfo inf = MouseInfo.getPointerInfo();
            Point mp = inf.getLocation();
            lblDrag.setLocation(mp.x-215,mp.y-60);
            lblDrag.setText(tblLoading.getValueAt(r, 1).toString());
            isClicked=true;
            tbl = "ld";
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLoadingMouseClicked

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked

        if(isClicked)
        {
            
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pr"))
            {
                r = tblPreProcess.getSelectedRow();
                id = tblPreProcess.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("loading");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("preprocess", jScrollPane6, tblPreProcess);
            
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void tblPreProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPreProcessMouseClicked

        if(isClicked)
        {
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("Preprocess");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("preprocess", jScrollPane6, tblPreProcess);
            
        }
        
        else
        {
            int r = tblPreProcess.getSelectedRow();
            Point wp = this.getLocation();
            PointerInfo inf = MouseInfo.getPointerInfo();
            Point mp = inf.getLocation();
            lblDrag.setLocation(mp.x-215,mp.y-60);
            lblDrag.setText(tblPreProcess.getValueAt(r, 1).toString());
            isClicked=true;
            tbl = "pr";
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPreProcessMouseClicked

    private void tblPreProcessMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPreProcessMouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPreProcessMouseMoved

    private void jScrollPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseClicked

        if(isClicked)
        {
            
            lblDrag.setText("");
            lblDrag.setLocation(0,0);
            isClicked=false;
            Emp d = new Emp();
            String id;
            int r;
            if(tbl.equals("emp"))
            {
                r = tblEmp.getSelectedRow();
                id = tblEmp.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
                
            }
            else if(tbl.equals("gr"))
            {
                r = tblGrind.getSelectedRow();
                id = tblGrind.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("pk"))
            {
                r = tblPacking.getSelectedRow();
                id = tblPacking.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            else if(tbl.equals("ld"))
            {
                r = tblLoading.getSelectedRow();
                id = tblLoading.getValueAt(r, 0).toString();
                d.setEmpId(Integer.parseInt(id));
            }
            d.setSection("Preprocess");
            EmpDAO dao = new EmpDAO();
            dao.updateEmpSection(d);
            loadTable("n/a", jScrollPane1, tblEmp);
        loadTable("grinding", jScrollPane2, tblGrind);
        loadTable("packing", jScrollPane3, tblPacking);
        loadTable("loading", jScrollPane4, tblLoading);
        loadTable("Preprocess", jScrollPane6, tblPreProcess);
            
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6MouseClicked

    private void jScrollPane6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseMoved

        Point wp = this.getLocation();
        PointerInfo inf = MouseInfo.getPointerInfo();
        Point mp = inf.getLocation();
        if(isClicked)
        {
            lblDrag.setLocation(mp.x-215,mp.y-60);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6MouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

//        jButton1.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        boolean b = true;
        Cal c = new Cal();
        String date = null;
        try {
            date = c.formatedDate(dch1.getDate().toString());
        } catch (Exception e) {
            b = false;
        }
        if(b)
        {
            if(c.isValid(date))
            {
                HashMap hm = new HashMap();
                hm.put("PARA_DATE", date);
                ReportView rv = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\WorkHistory.jasper", hm);
                rv.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Please select a valid date");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Please select a date");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllocateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllocateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private com.toedter.calendar.JDateChooser dch1;
    private javax.swing.JButton home4;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblDrag;
    private javax.swing.JButton logout;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblGrind;
    private javax.swing.JTable tblLoading;
    private javax.swing.JTable tblPacking;
    private javax.swing.JTable tblPreProcess;
    // End of variables declaration//GEN-END:variables
}
