/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appPackage;

import DAO.EmpDAO;
import DAO.LoginDAO;
import data.AutoCompletion;
import data.ReportView;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ChangeUnPw extends javax.swing.JFrame {
    
    boolean confPw = false;

    /**
     * Creates new form ChangeUnPw
     */
    public ChangeUnPw() {
        initComponents();
        LoginDAO d = new LoginDAO();
        txtChangeUser.setText(d.getun());
        EmpDAO dao = new EmpDAO();
        
        String emplevel = dao.getEmpLevel(txtChangeUser.getText());
        System.out.println(emplevel);
        if(emplevel.equalsIgnoreCase("manager"))
        {
            btnViewComps.setVisible(true);
        }
        else
        {
            btnViewComps.setVisible(false);
        }
        fillEmpNames();
        AutoCompletion.enable(cmbNames);
//        jPanel1.setBackground(new Color(0, 0, 0, 0));
//        txtChangeUser.setBackground(new Color(0, 0, 0, 0));
        txtCurrentPw.setEnabled(false);
        txtNewPw.setEnabled(false);
        txtConfirmPw.setEnabled(false);
        txtNewUn.setEnabled(false);
        chkUn.setEnabled(false);
        chkPw.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel5.setEnabled(false);
        jLabel6.setEnabled(false);
        jLabel7.setEnabled(false);
        btnSubmit.setEnabled(false);
        lblECPw.setText(" ");
        lblEnotAvailable.setText(" ");
        jLabel2.setEnabled(false);
            jLabel8.setEnabled(false);
            cmbNames.setEnabled(false);
            txtComp.setEnabled(false);
            btnAddComp.setEnabled(false);
    }
    
    String getPWStrength(String pw)
    {
        if(pw.length()<8)
        {
            return "weak";
        }
        else if(pw.length()>7 && pw.length()< 13)
        {
            return "medium";
        }
        else
        {
            return "strong";
        }
    }
    
    private void fillEmpNames() {
        EmpDAO dao = new EmpDAO();
        ArrayList nameList = dao.getEmpNames();
        cmbNames.removeAllItems();
        cmbNames.addItem("");
        Iterator i = nameList.iterator();

        while (i.hasNext()) {
           cmbNames.addItem(i.next());
        }

//        String jobCatName = cmbNames.getSelectedItem().toString();

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtChangeUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdoUsername = new javax.swing.JRadioButton();
        chkUn = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtNewUn = new javax.swing.JTextField();
        chkPw = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtCurrentPw = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtNewPw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmPw = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        lblECPw = new javax.swing.JLabel();
        lblEPassword = new javax.swing.JLabel();
        lblECpassword = new javax.swing.JLabel();
        lblEnotAvailable = new javax.swing.JLabel();
        lblEConfPw = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rdoComp = new javax.swing.JRadioButton();
        cmbNames = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComp = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnAddComp = new javax.swing.JButton();
        lblEComp = new javax.swing.JLabel();
        lblEAbout = new javax.swing.JLabel();
        btnViewComps = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        dchMonth = new com.toedter.calendar.JMonthChooser();
        dchYear = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        jLabel3.setText("Welcome");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rdoUsername.setText("Change Usernsme & Password");
        rdoUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoUsernameActionPerformed(evt);
            }
        });

        chkUn.setText("Change Username");
        chkUn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUnActionPerformed(evt);
            }
        });

        jLabel4.setText("New Username");

        txtNewUn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewUnFocusLost(evt);
            }
        });

        chkPw.setText("Change Password");
        chkPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPwActionPerformed(evt);
            }
        });

        jLabel5.setText("Current Password");

        txtCurrentPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentPwActionPerformed(evt);
            }
        });
        txtCurrentPw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCurrentPwFocusGained(evt);
            }
        });

        jLabel6.setText("New Password");

        txtNewPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPwKeyReleased(evt);
            }
        });

        jLabel7.setText("Confirm Password");

        txtConfirmPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPwKeyReleased(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblECPw.setForeground(new java.awt.Color(255, 0, 0));
        lblECPw.setText("Password Incorrect");

        lblEPassword.setText(" ");

        lblEnotAvailable.setForeground(new java.awt.Color(255, 0, 0));
        lblEnotAvailable.setText("Username Not Available");

        lblEConfPw.setForeground(new java.awt.Color(255, 0, 0));
        lblEConfPw.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnSubmit)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEConfPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtConfirmPw, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                        .addComponent(lblECpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPw)
                            .addComponent(chkUn)
                            .addComponent(rdoUsername)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel6)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEnotAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblECPw)
                            .addComponent(txtNewUn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtNewPw)
                            .addComponent(txtCurrentPw)
                            .addComponent(lblEPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoUsername)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCurrentPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblECPw)
                .addGap(6, 6, 6)
                .addComponent(chkUn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNewUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnotAvailable)
                .addGap(11, 11, 11)
                .addComponent(chkPw)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNewPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblECpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtConfirmPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(lblEConfPw)
                .addGap(1, 1, 1)
                .addComponent(btnSubmit)
                .addGap(23, 23, 23))
        );

        rdoComp.setText("Add Complain");
        rdoComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCompActionPerformed(evt);
            }
        });

        cmbNames.setEditable(true);
        cmbNames.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbNamesFocusGained(evt);
            }
        });

        jLabel2.setText("About ");

        txtComp.setColumns(20);
        txtComp.setRows(5);
        txtComp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCompFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(txtComp);

        jLabel8.setText("Complain");

        btnAddComp.setText("Add Complain");
        btnAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompActionPerformed(evt);
            }
        });

        lblEComp.setForeground(new java.awt.Color(255, 0, 0));
        lblEComp.setText(" ");

        lblEAbout.setForeground(new java.awt.Color(255, 0, 0));
        lblEAbout.setText(" ");

        btnViewComps.setText("View Complains");
        btnViewComps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCompsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoComp)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNames, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewComps)
                    .addComponent(btnAddComp))
                .addGap(101, 101, 101))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addComponent(lblEAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEComp)
                .addGap(50, 50, 50)
                .addComponent(btnAddComp)
                .addGap(30, 30, 30)
                .addComponent(btnViewComps)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton1.setText("Work History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtChangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dchYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dchMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtChangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(dchMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dchYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCurrentPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentPwActionPerformed

    private void rdoUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoUsernameActionPerformed

        if(rdoUsername.isSelected())
        {
            txtCurrentPw.setEnabled(true);
            chkUn.setEnabled(true);
            chkPw.setEnabled(true);
            jLabel5.setEnabled(true);

        }
        else
        {
            chkUn.setSelected(false);
            chkPw.setSelected(false);
            txtCurrentPw.setEnabled(false);
            txtNewPw.setEnabled(false);
            txtConfirmPw.setEnabled(false);
            txtNewUn.setEnabled(false);
            chkUn.setEnabled(false);
            chkPw.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel6.setEnabled(false);
            jLabel7.setEnabled(false);
            btnSubmit.setEnabled(false);
            lblECPw.setText(" ");
            lblEnotAvailable.setText(" ");
            
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoUsernameActionPerformed

    private void chkUnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUnActionPerformed

        if(chkUn.isSelected())
        {
            txtNewUn.setEnabled(true);
            jLabel4.setEnabled(true);
            btnSubmit.setEnabled(true);
        }
        else
        {
            txtNewUn.setEnabled(false);
            jLabel4.setEnabled(false);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_chkUnActionPerformed

    private void chkPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPwActionPerformed

        if(chkPw.isSelected())
        {
            txtNewPw.setEnabled(true);
//            txtConfirmPw.setEnabled(true);
            jLabel6.setEnabled(true);
//            jLabel7.setEnabled(true);
            btnSubmit.setEnabled(true);
            lblEPassword.setEnabled(true);
            lblECpassword.setEnabled(true);
            
        }
        else
        {
            txtNewPw.setEnabled(false);
            txtConfirmPw.setEnabled(false);
            jLabel6.setEnabled(false);
            jLabel7.setEnabled(false);
            lblEPassword.setEnabled(false);
            lblECpassword.setEnabled(false);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPwActionPerformed

    private void txtNewPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPwKeyReleased

        
            String st = getPWStrength(txtNewPw.getText());
            if(st.equalsIgnoreCase("weak"))
            {
                lblEPassword.setForeground(Color.red);
                txtConfirmPw.setEnabled(false);
                jLabel7.setEnabled(false);
////                confPw = false;
            }
            else
            {
                lblEPassword.setForeground(Color.black);
                txtConfirmPw.setEnabled(true);
                jLabel7.setEnabled(true);
//                confPw=true;
            }
            lblEPassword.setText("Strength : "+st);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPwKeyReleased

    private void txtConfirmPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPwKeyReleased

        if(!txtNewPw.getText().equals(txtConfirmPw.getText()))
            {
//                lblECpassword.setText("X");
                lblECpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png")));
                confPw = false;
//                check = false;
            }
            else
            {
//                lblECpassword.setText("  ");
                lblECpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png")));
                confPw = true;
            }
        
        System.out.println(confPw);
        
        
//        if(txtPassword.getText().equals(""))
//        {
//            JOptionPane.showMessageDialog(rootPane, "Please enter a new Password first");
//            txtCPassword.setText("");
//        }
//        else if(getPWStrength(txtPassword.getText()).equalsIgnoreCase("weak"))
//        {
//            JOptionPane.showMessageDialog(rootPane, "Please enter atleast a medium strenth password");
//            txtCPassword.setText("");
//        }
//        else 
//        {
//            if(!txtPassword.getText().equals(txtCPassword.getText()))
//            {
////                lblECpassword.setText("X");
//                lblECpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png")));
////                check = false;
//            }
//            else
//            {
////                lblECpassword.setText("  ");
//                lblECpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png")));
//            }
//        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPwKeyReleased

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String un = txtChangeUser.getText();
        String pw = txtCurrentPw.getText();
        String newun = txtNewUn.getText();
        String newpw = txtNewPw.getText();
        
        
        LoginDAO d = new LoginDAO();
        boolean isValid = d.validateUser(un, pw);
        String id = d.getEmpId(un)+"";
        if(isValid)
        {
            System.out.println("valid");
            EmpDAO dao = new EmpDAO();
            
            if(chkPw.isSelected())
            {
                boolean b = true;
                if(txtNewUn.getText().equals(""))
                {
                    lblEnotAvailable.setText("Username Can't be empty");
                    b=false;
                }
                if(confPw && b)
                {
                    dao.updateUnPw(id, newun, newpw);
                    d.setUn(newun);
                    JOptionPane.showMessageDialog(rootPane, "successsuccessfully Updated");
                    txtChangeUser.setText(newun);
                    rdoUsername.setSelected(false);
                    chkUn.setSelected(false);
                    chkPw.setSelected(false);
                    txtCurrentPw.setEnabled(false);
                    txtNewPw.setEnabled(false);
                    txtConfirmPw.setEnabled(false);
                    txtNewUn.setEnabled(false);
                    chkUn.setEnabled(false);
                    chkPw.setEnabled(false);
                    jLabel4.setEnabled(false);
                    jLabel5.setEnabled(false);
                    jLabel6.setEnabled(false);
                    jLabel7.setEnabled(false);
                    btnSubmit.setEnabled(false);
                    lblECPw.setText(" ");
                    lblEnotAvailable.setText(" ");
                    lblEPassword.setEnabled(false);
                    lblECpassword.setEnabled(false);
                }
                else
                {
                    lblEConfPw.setText("Incorrect Password");
                }
            }
            else
            {
                if(txtNewUn.getText().equals(""))
                {
                    lblEnotAvailable.setText("Username Can't be empty");
                }
                else
                {
                    dao.updateUnPw(id, newun, ""); 
                    d.setUn(newun);
                    txtChangeUser.setText(newun);
                    JOptionPane.showMessageDialog(rootPane, "successfully Updated");
                }
            }
        }
        else
        {
            System.out.println("invalid");
            lblECPw.setText("Password Incorrect");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtCurrentPwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPwFocusGained

        lblECPw.setText(" ");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentPwFocusGained

    private void txtNewUnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewUnFocusLost

        LoginDAO dao = new LoginDAO();
        if(!txtNewUn.getText().equals("") && !dao.isAvailable(txtNewUn.getText()))
        {
            lblEnotAvailable.setText("Username Not Available");
        }
        else
        {
            lblEnotAvailable.setText(" ");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewUnFocusLost

    private void btnAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompActionPerformed

        String empid ="";
        if(!cmbNames.getSelectedItem().toString().equals(""))
        {
            empid = cmbNames.getSelectedItem().toString().split(" ")[2];
//            JOptionPane.showMessageDialog(rootPane, empid);
            if(txtComp.getText().equals(""))
            {
                lblEComp.setText("Complain field is empty");
            }
            else
            {
                EmpDAO dao = new EmpDAO();
                dao.addComp(empid, txtComp.getText());
            }
            
        }
        else
        {
            lblEAbout.setText("Select Employee");
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCompActionPerformed

    private void rdoCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCompActionPerformed

        if(rdoComp.isSelected())
        {
            jLabel2.setEnabled(true);
            jLabel8.setEnabled(true);
            cmbNames.setEnabled(true);
            txtComp.setEnabled(true);
            btnAddComp.setEnabled(true);
            
        }
        else
        {
            jLabel2.setEnabled(false);
            jLabel8.setEnabled(false);
            cmbNames.setEnabled(false);
            txtComp.setEnabled(false);
            btnAddComp.setEnabled(false);
            lblEAbout.setText(" ");
            lblEComp.setText(" ");
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoCompActionPerformed

    private void cmbNamesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbNamesFocusGained

            lblEAbout.setText(" ");

        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNamesFocusGained

    private void txtCompFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompFocusGained

          lblEComp.setText(" ");

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompFocusGained

    private void btnViewCompsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCompsActionPerformed

        new Complains().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCompsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String year = dchYear.getYear()+"";
        String month = (dchMonth.getMonth()+1)+"";
        System.out.println(year+" "+month);
        String m;
        if(month.length()==1)
        {
            m = year+"-0"+month+"-%";
        }
        else
        {
            m = year+"-"+month+"-%";
        }
        System.out.println(m);
        String un = txtChangeUser.getText();
        LoginDAO d = new LoginDAO();
        String id = d.getEmpId(un)+"";
        HashMap hm = new HashMap();
        hm.put("PARA_MONTH", m);
        hm.put("PARA_ID", id);
        hm.put("PARA_NAME", un);
        ReportView rv = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\history.jasper", hm);
        rv.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a =JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if(a == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUnPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUnPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUnPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUnPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeUnPw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComp;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewComps;
    private javax.swing.JCheckBox chkPw;
    private javax.swing.JCheckBox chkUn;
    private javax.swing.JComboBox cmbNames;
    private com.toedter.calendar.JMonthChooser dchMonth;
    private com.toedter.calendar.JYearChooser dchYear;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEAbout;
    private javax.swing.JLabel lblECPw;
    private javax.swing.JLabel lblEComp;
    private javax.swing.JLabel lblEConfPw;
    private javax.swing.JLabel lblECpassword;
    private javax.swing.JLabel lblEPassword;
    private javax.swing.JLabel lblEnotAvailable;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JRadioButton rdoComp;
    private javax.swing.JRadioButton rdoUsername;
    public static javax.swing.JTextField txtChangeUser;
    private javax.swing.JTextArea txtComp;
    private javax.swing.JPasswordField txtConfirmPw;
    private javax.swing.JPasswordField txtCurrentPw;
    private javax.swing.JPasswordField txtNewPw;
    private javax.swing.JTextField txtNewUn;
    // End of variables declaration//GEN-END:variables
}
