/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackage;

import DAO.EmpDAO;
import DAO.LoginDAO;
import data.Animation;
import data.Cal;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sanke
 */
public class MainMenu extends javax.swing.JFrame {

    public static boolean b = true;
    public static String level;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        hideAll();
    }

    Animation anm = new Animation();

    public void hideAll() {
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPay3 = new javax.swing.JButton();
        btnSto4 = new javax.swing.JButton();
        btnOut2 = new javax.swing.JButton();
        btnSto1 = new javax.swing.JButton();
        btnSup3 = new javax.swing.JButton();
        btnEmp1 = new javax.swing.JButton();
        btnPay1 = new javax.swing.JButton();
        btnDel3 = new javax.swing.JButton();
        btnOut1 = new javax.swing.JButton();
        btnOut4 = new javax.swing.JButton();
        btnPro4 = new javax.swing.JButton();
        btnSup1 = new javax.swing.JButton();
        btnDel2 = new javax.swing.JButton();
        btnPro3 = new javax.swing.JButton();
        btnSup4 = new javax.swing.JButton();
        btnPro1 = new javax.swing.JButton();
        btnCust2 = new javax.swing.JButton();
        btnOut3 = new javax.swing.JButton();
        btnEmp4 = new javax.swing.JButton();
        btnSto3 = new javax.swing.JButton();
        btnCust3 = new javax.swing.JButton();
        btnPro2 = new javax.swing.JButton();
        btnPay2 = new javax.swing.JButton();
        btnSto2 = new javax.swing.JButton();
        btnCust1 = new javax.swing.JButton();
        btnEmp3 = new javax.swing.JButton();
        btnPay4 = new javax.swing.JButton();
        btnCust4 = new javax.swing.JButton();
        btnSup2 = new javax.swing.JButton();
        btnDel4 = new javax.swing.JButton();
        btnDel1 = new javax.swing.JButton();
        btnEmp2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnOut = new javax.swing.JButton();
        btnSup = new javax.swing.JButton();
        btnPro = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnSto = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btncust = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        lblUser.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, -1, -1));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jPanel1.setOpaque(false);

        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/reports.png"))); // NOI18N
        btnPay3.setText("Reports");
        btnPay3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_reports.png"))); // NOI18N
        btnPay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPay3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 150, 45));

        btnSto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/emp_Allocate.png"))); // NOI18N
        btnSto4.setText("Allocate");
        btnSto4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Allocate.png"))); // NOI18N
        btnSto4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Remove.png"))); // NOI18N
        btnSto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSto4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 150, 45));

        btnOut2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/stock_Update.png"))); // NOI18N
        btnOut2.setText("Update");
        btnOut2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_stock_Update.png"))); // NOI18N
        btnOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOut2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, 45));

        btnSto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/emp_Add.png"))); // NOI18N
        btnSto1.setText("Add");
        btnSto1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Add.png"))); // NOI18N
        btnSto1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Allocate.png"))); // NOI18N
        btnSto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSto1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 45));

        btnSup3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supplier_Remove .png"))); // NOI18N
        btnSup3.setText("Rremove");
        btnSup3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_supplier_Remove.png"))); // NOI18N
        btnSup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSup3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 150, 45));

        btnEmp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/pament_update.png"))); // NOI18N
        btnEmp1.setText("Payments");
        btnEmp1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_pament_update.png"))); // NOI18N
        btnEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmp1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 150, 45));

        btnPay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/manageprofit.png"))); // NOI18N
        btnPay1.setText("Transactions");
        btnPay1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_manageprofit.png"))); // NOI18N
        btnPay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPay1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 45));

        btnDel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/deliveryVehicle_Remove.png"))); // NOI18N
        btnDel3.setText("Remove");
        btnDel3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_deliveryVehicle_Remove.png"))); // NOI18N
        btnDel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 150, 45));

        btnOut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/stock_add.png"))); // NOI18N
        btnOut1.setText("Add");
        btnOut1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_stock_add.png"))); // NOI18N
        btnOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOut1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 45));

        btnOut4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/stock_Manage.png"))); // NOI18N
        btnOut4.setText("Manage");
        btnOut4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_stock_Manage.png"))); // NOI18N
        btnOut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOut4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 150, 45));

        btnPro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Outlet_cust_Remove.png"))); // NOI18N
        btnPro4.setText("Remove");
        btnPro4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_Outlet_cust_Remove.png"))); // NOI18N
        btnPro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPro4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 150, 45));

        btnSup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supplier_add.png"))); // NOI18N
        btnSup1.setText("Add");
        btnSup1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_supplier_add.png"))); // NOI18N
        btnSup1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_supplier_add.png"))); // NOI18N
        btnSup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSup1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 150, 45));

        btnDel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/deliveryVehicle_Update.png"))); // NOI18N
        btnDel2.setText("Update");
        btnDel2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_deliveryVehicle_Update.png"))); // NOI18N
        btnDel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, 45));

        btnPro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Outlet_cust_Update.png"))); // NOI18N
        btnPro3.setText("Update");
        btnPro3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_Outlet_cust_update copy.png"))); // NOI18N
        btnPro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPro3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, 45));

        btnSup4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_stock_Update.png"))); // NOI18N
        btnSup4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSup4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSup4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 150, 45));

        btnPro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/poinOfSales.png"))); // NOI18N
        btnPro1.setText("Outlet");
        btnPro1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_poinOfSales.png"))); // NOI18N
        btnPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPro1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 45));

        btnCust2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/delivery_add _Remove.png"))); // NOI18N
        btnCust2.setText("Update");
        btnCust2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_delivery_Update.png"))); // NOI18N
        btnCust2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCust2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 150, 45));

        btnOut3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/stock_Remove.png"))); // NOI18N
        btnOut3.setText("Remove");
        btnOut3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_stock_Remove.png"))); // NOI18N
        btnOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOut3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 150, 45));

        btnEmp4.setText("   ");
        btnEmp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmp4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 150, 45));

        btnSto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/emp_Remove.png"))); // NOI18N
        btnSto3.setText("Remove");
        btnSto3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Remove.png"))); // NOI18N
        btnSto3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Update .png"))); // NOI18N
        btnSto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSto3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 150, 45));

        btnCust3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/delivery_add-Remove.png"))); // NOI18N
        btnCust3.setText("Remove");
        btnCust3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_delivery_Remove.png"))); // NOI18N
        btnCust3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCust3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 150, 45));

        btnPro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Outlet_cust.png"))); // NOI18N
        btnPro2.setText("Add");
        btnPro2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_Outlet_cust.png"))); // NOI18N
        btnPro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPro2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, 45));

        btnPay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/loan.png"))); // NOI18N
        btnPay2.setText("Loan");
        btnPay2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_loan.png"))); // NOI18N
        btnPay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPay2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, 45));

        btnSto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/emp_Update.png"))); // NOI18N
        btnSto2.setText("Update");
        btnSto2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Update .png"))); // NOI18N
        btnSto2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_emp_Add.png"))); // NOI18N
        btnSto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSto2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 150, 45));

        btnCust1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/delivery_add.png"))); // NOI18N
        btnCust1.setText("Add");
        btnCust1.setOpaque(false);
        btnCust1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_delivery_add.png"))); // NOI18N
        btnCust1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCust1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 45));

        btnEmp3.setText("   ");
        btnEmp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmp3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 150, 45));

        btnPay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPay4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPay4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 150, 45));

        btnCust4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_supplier_Update.png"))); // NOI18N
        btnCust4.setText("Del Orders");
        btnCust4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCust4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 150, 45));

        btnSup2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/supplier_Update.png"))); // NOI18N
        btnSup2.setText("Update");
        btnSup2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_supplier_Update.png"))); // NOI18N
        btnSup2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_supplier_Update.png"))); // NOI18N
        btnSup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSup2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 150, 45));

        btnDel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/deliveryVehicle_Maintainence.png"))); // NOI18N
        btnDel4.setText("Maintanance");
        btnDel4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_deliveryVehicle_Maintainence.png"))); // NOI18N
        btnDel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 150, 45));

        btnDel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/deliveryVehicle_add.png"))); // NOI18N
        btnDel1.setText("Add");
        btnDel1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_deliveryVehicle_add.png"))); // NOI18N
        btnDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 45));

        btnEmp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_payroll_attendence.png"))); // NOI18N
        btnEmp2.setText("Attendance");
        btnEmp2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImg/Focus_payroll_attendence.png"))); // NOI18N
        btnEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmp2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 45));

        jPanel3.setOpaque(false);

        btnOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock.png"))); // NOI18N
        btnOut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_stock.png"))); // NOI18N
        btnOut.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_stock.png"))); // NOI18N
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        btnSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/suplier.png"))); // NOI18N
        btnSup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_suplier.png"))); // NOI18N
        btnSup.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_suplier.png"))); // NOI18N
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        btnPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/outlet.png"))); // NOI18N
        btnPro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_outlet.png"))); // NOI18N
        btnPro.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_outlet.png"))); // NOI18N
        btnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProActionPerformed(evt);
            }
        });

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delivery.png"))); // NOI18N
        btnDel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delivery.png"))); // NOI18N
        btnDel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delivery.png"))); // NOI18N
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profit.png"))); // NOI18N
        btnPay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_profit.png"))); // NOI18N
        btnPay.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_profit.png"))); // NOI18N
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnSto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee.png"))); // NOI18N
        btnSto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_employee.png"))); // NOI18N
        btnSto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_employee.png"))); // NOI18N
        btnSto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoActionPerformed(evt);
            }
        });

        btnEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payroll.png"))); // NOI18N
        btnEmp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_payroll.png"))); // NOI18N
        btnEmp.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_payroll.png"))); // NOI18N
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btncust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCust.png"))); // NOI18N
        btncust.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_btnCust.png"))); // NOI18N
        btncust.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_btnCust.png"))); // NOI18N
        btncust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncustMouseEntered(evt);
            }
        });
        btncust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmp)
                    .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSup)
                    .addComponent(btnSto)
                    .addComponent(btnDel)
                    .addComponent(btncust)))
            .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEmp, btnOut, btnPay, btnPro});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(btncust, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnSto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnOut, btnPay, btnPro, btnSto, btnSup});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 127, 940, 440));

        lbldate.setFont(new java.awt.Font("LcdD", 0, 24)); // NOI18N
        lbldate.setText("date");
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 110, -1));

        lbltime.setFont(new java.awt.Font("LcdD", 0, 24)); // NOI18N
        lbltime.setText("time");
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustActionPerformed
        anm.showbtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);


    }//GEN-LAST:event_btncustActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.showbtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.showbtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.showbtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnProActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.showbtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnSupActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.showbtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.showbtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.hidebtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnStoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoActionPerformed
        anm.hidebtn(btnCust1, btnCust2, btnCust3, btnCust4);
        anm.hidebtn(btnDel1, btnDel2, btnDel3, btnDel4);
        anm.hidebtn(btnEmp1, btnEmp2, btnEmp3, btnEmp4);
        anm.hidebtn(btnOut1, btnOut2, btnOut3, btnOut4);
        anm.hidebtn(btnPay1, btnPay2, btnPay3, btnPay4);
        anm.hidebtn(btnPro1, btnPro2, btnPro3, btnPro4);
        anm.hidebtn(btnSup1, btnSup2, btnSup3, btnSup4);
        anm.showbtn(btnSto1, btnSto2, btnSto3, btnSto4);
    }//GEN-LAST:event_btnStoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        if (!b) {
            this.dispose();
            new Login().setVisible(true);
        }
        LoginDAO d = new LoginDAO();
        
        lblUser.setText(d.getun());

        btncust.setBackground(new Color(0, 0, 0, 0));
        btnDel.setBackground(new Color(0, 0, 0, 0));
        btnEmp.setBackground(new Color(0, 0, 0, 0));
        btnPay.setBackground(new Color(0, 0, 0, 0));
        btnSto.setBackground(new Color(0, 0, 0, 0));
        btnPro.setBackground(new Color(0, 0, 0, 0));
        btnOut.setBackground(new Color(0, 0, 0, 0));
        btnSup.setBackground(new Color(0, 0, 0, 0));
        btnEmp.setBackground(new Color(0, 0, 0, 0));
        btnExit.setBackground(new Color(0, 0, 0, 0));
        logout.setBackground(new Color(0, 0, 0, 0));
        home.setBackground(new Color(0, 0, 0, 0));

        btnCust1.setBackground(new Color(0, 0, 0, 0));
        btnCust2.setBackground(new Color(0, 0, 0, 0));
        btnCust3.setBackground(new Color(0, 0, 0, 0));
        btnCust4.setBackground(new Color(0, 0, 0, 0));
        btnDel1.setBackground(new Color(0, 0, 0, 0));
        btnDel2.setBackground(new Color(0, 0, 0, 0));
        btnDel3.setBackground(new Color(0, 0, 0, 0));
        btnDel4.setBackground(new Color(0, 0, 0, 0));
        btnEmp1.setBackground(new Color(0, 0, 0, 0));
        btnEmp2.setBackground(new Color(0, 0, 0, 0));
        btnEmp3.setBackground(new Color(0, 0, 0, 0));
        btnEmp4.setBackground(new Color(0, 0, 0, 0));
        btnOut1.setBackground(new Color(0, 0, 0, 0));
        btnOut2.setBackground(new Color(0, 0, 0, 0));
        btnOut3.setBackground(new Color(0, 0, 0, 0));
        btnOut4.setBackground(new Color(0, 0, 0, 0));
        btnPay1.setBackground(new Color(0, 0, 0, 0));
        btnPay2.setBackground(new Color(0, 0, 0, 0));
        btnPay3.setBackground(new Color(0, 0, 0, 0));
        btnPay4.setBackground(new Color(0, 0, 0, 0));
        btnPro1.setBackground(new Color(0, 0, 0, 0));
        btnPro2.setBackground(new Color(0, 0, 0, 0));
        btnPro3.setBackground(new Color(0, 0, 0, 0));
        btnPro4.setBackground(new Color(0, 0, 0, 0));
        btnSup1.setBackground(new Color(0, 0, 0, 0));
        btnSup2.setBackground(new Color(0, 0, 0, 0));
        btnSup3.setBackground(new Color(0, 0, 0, 0));
        btnSup4.setBackground(new Color(0, 0, 0, 0));
        btnSto1.setBackground(new Color(0, 0, 0, 0));
        btnSto2.setBackground(new Color(0, 0, 0, 0));
        btnSto3.setBackground(new Color(0, 0, 0, 0));
        btnSto4.setBackground(new Color(0, 0, 0, 0));

        Cal c = new Cal();
        c.setDateTime(lbldate, lbltime);

        EmpDAO dao = new EmpDAO();
        level = dao.getEmpLevel(lblUser.getText());
        System.out.println(level);
        if (!level.equals("Manager")) {
            btnSto.setEnabled(false);
            btnPay.setEnabled(false);
        }
        if (level.equals("Cashier")) {
            btncust.setEnabled(false);
            btnDel.setEnabled(false);
        }
        if (level.equals("Store Keeper")) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btncustMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncustMouseEntered

    }//GEN-LAST:event_btncustMouseEntered

    private void btnCust1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust1ActionPerformed

        Customer c = new Customer();
        c.jtb11.setSelectedIndex(0);
        c.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCust1ActionPerformed

    private void btnSto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSto1ActionPerformed

        manageEmp m = new manageEmp();
        m.jTabbedPane1.setSelectedIndex(0);
        m.setVisible(true);
        this.dispose();
//        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSto1ActionPerformed

    private void btnSto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSto2ActionPerformed

        manageEmp m = new manageEmp();
        m.jTabbedPane1.setSelectedIndex(1);
        m.setVisible(true);
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnSto2ActionPerformed

    private void btnSto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSto3ActionPerformed

        manageEmp m = new manageEmp();
        m.jTabbedPane1.setSelectedIndex(2);
        m.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSto3ActionPerformed

    private void btnSto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSto4ActionPerformed

        AllocateEmployee a = new AllocateEmployee();
        a.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSto4ActionPerformed

    private void btnPay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPay1ActionPerformed

        Profit p = new Profit();
        p.General.setSelectedIndex(0);
        p.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPay1ActionPerformed

    private void btnPay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPay2ActionPerformed

        Profit p = new Profit();
        p.General.setSelectedIndex(1);
        p.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPay2ActionPerformed

    private void btnPay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPay3ActionPerformed

        Profit p = new Profit();
        p.General.setSelectedIndex(2);
        p.setVisible(true);
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnPay3ActionPerformed

    private void btnPay4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPay4ActionPerformed

        Profit p = new Profit();
        p.General.setSelectedIndex(3);
        p.setVisible(true);
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnPay4ActionPerformed

    private void btnDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel1ActionPerformed

        Delivery d = new Delivery();
        d.jTabbedPane1.setSelectedIndex(0);
        d.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDel1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        Login l = new Login();
        l.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        ChangeUnPw ch = new ChangeUnPw();
        ch.txtChangeUser.setText(lblUser.getText());
        ch.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void btnCust2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust2ActionPerformed

        Customer c = new Customer();
        c.jtb11.setSelectedIndex(1);
        c.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCust2ActionPerformed

    private void btnCust3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust3ActionPerformed

        Customer c = new Customer();
        c.jtb11.setSelectedIndex(2);
        c.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCust3ActionPerformed

    private void btnDel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel2ActionPerformed

        Delivery d = new Delivery();
        d.jTabbedPane1.setSelectedIndex(1);
        d.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDel2ActionPerformed

    private void btnDel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel3ActionPerformed

        Delivery d = new Delivery();
        d.jTabbedPane1.setSelectedIndex(2);
        d.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDel3ActionPerformed

    private void btnDel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel4ActionPerformed

        Delivery d = new Delivery();
        d.jTabbedPane1.setSelectedIndex(3);
        d.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDel4ActionPerformed

    private void btnEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmp1ActionPerformed

        Payroll p = new Payroll();
        p.jTabbedPane2.setSelectedIndex(0);
        p.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmp1ActionPerformed

    private void btnEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmp2ActionPerformed

        Payroll p = new Payroll();
        p.jTabbedPane2.setSelectedIndex(1);
        p.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnEmp2ActionPerformed

    private void btnEmp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmp3ActionPerformed

    private void btnEmp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmp4ActionPerformed

    private void btnOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOut1ActionPerformed

        products p = new products();
        p.jTabbedPane1.setSelectedIndex(0);
        p.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOut1ActionPerformed

    private void btnOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOut2ActionPerformed

        products p = new products();
        p.jTabbedPane1.setSelectedIndex(1);
        p.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOut2ActionPerformed

    private void btnOut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOut3ActionPerformed

        products p = new products();
        p.jTabbedPane1.setSelectedIndex(2);
        p.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnOut3ActionPerformed

    private void btnOut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOut4ActionPerformed

        stock s = new stock();
        s.jTabbedPane1.setSelectedIndex(0);
        s.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnOut4ActionPerformed

    private void btnPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPro1ActionPerformed

        Outlet o = new Outlet();
        o.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPro1ActionPerformed

    private void btnPro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPro2ActionPerformed

        OutletCustomerGUI oc = new OutletCustomerGUI();
        oc.tplOutletCustomer.setSelectedIndex(0);
        oc.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPro2ActionPerformed

    private void btnPro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPro3ActionPerformed

        OutletCustomerGUI oc = new OutletCustomerGUI();
        oc.tplOutletCustomer.setSelectedIndex(1);
        oc.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnPro3ActionPerformed

    private void btnPro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPro4ActionPerformed

        OutletCustomerGUI oc = new OutletCustomerGUI();
        oc.tplOutletCustomer.setSelectedIndex(2);
        oc.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPro4ActionPerformed

    private void btnSup4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSup4ActionPerformed

        MakeOrder m = new MakeOrder();
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSup4ActionPerformed

    private void btnSup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSup1ActionPerformed

        Supplier s = new Supplier();
        s.jTabbedPane1.setSelectedIndex(0);
        s.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSup1ActionPerformed

    private void btnSup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSup2ActionPerformed

        Supplier s = new Supplier();
        s.jTabbedPane1.setSelectedIndex(1);
        s.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSup2ActionPerformed

    private void btnSup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSup3ActionPerformed

        Supplier s = new Supplier();
        s.jTabbedPane1.setSelectedIndex(2);
        s.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSup3ActionPerformed

    private void btnCust4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust4ActionPerformed

        DeliveryOrder d = new DeliveryOrder();
        d.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnCust4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCust1;
    private javax.swing.JButton btnCust2;
    private javax.swing.JButton btnCust3;
    private javax.swing.JButton btnCust4;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDel1;
    private javax.swing.JButton btnDel2;
    private javax.swing.JButton btnDel3;
    private javax.swing.JButton btnDel4;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnEmp1;
    private javax.swing.JButton btnEmp2;
    private javax.swing.JButton btnEmp3;
    private javax.swing.JButton btnEmp4;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnOut1;
    private javax.swing.JButton btnOut2;
    private javax.swing.JButton btnOut3;
    private javax.swing.JButton btnOut4;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPay1;
    private javax.swing.JButton btnPay2;
    private javax.swing.JButton btnPay3;
    private javax.swing.JButton btnPay4;
    private javax.swing.JButton btnPro;
    private javax.swing.JButton btnPro1;
    private javax.swing.JButton btnPro2;
    private javax.swing.JButton btnPro3;
    private javax.swing.JButton btnPro4;
    private javax.swing.JButton btnSto;
    private javax.swing.JButton btnSto1;
    private javax.swing.JButton btnSto2;
    private javax.swing.JButton btnSto3;
    private javax.swing.JButton btnSto4;
    private javax.swing.JButton btnSup;
    private javax.swing.JButton btnSup1;
    private javax.swing.JButton btnSup2;
    private javax.swing.JButton btnSup3;
    private javax.swing.JButton btnSup4;
    private javax.swing.JButton btncust;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlBtn;
    // End of variables declaration//GEN-END:variables
}
