/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackage;

import DAO.CustomerDAO;
import DAO.SupplierDAO;
import static appPackage.Supplier.jTabbedPane1;
import data.Cal;
import data.SupplierDetails;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import Email.Mail;

/**
 *
 * @author Dell
 */
public class MakeOrder extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header; //Used to store data header

    public MakeOrder() {
        initComponents();
        header = new Vector<String>();
        header.add("Supplier ID");
        header.add("First Name");
        header.add("Last Name");
        header.add("Adress");
        header.add("Email");
        header.add("Phone");
        header.add("Account No");
        loadTable("");

    }

    private void loadTable(String no) {

        SupplierDAO dao = new SupplierDAO();
        data = dao.getSuppliertFiltered(no);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane1.setViewportView(tblSupplier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        txtquantity = new javax.swing.JTextField();
        lblmaterialname = new javax.swing.JLabel();
        lblquantiy = new javax.swing.JLabel();
        lblexpecteddate = new javax.swing.JLabel();
        txtmaterialname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnmakeorder = new javax.swing.JButton();
        lblsupplieremail = new javax.swing.JLabel();
        lblsuppliername = new javax.swing.JLabel();
        lblsuppliername1 = new javax.swing.JLabel();
        lblsupplieremail1 = new javax.swing.JLabel();
        expecteddate = new com.toedter.calendar.JDateChooser();
        lblmaterialname1 = new javax.swing.JLabel();
        lblquantity1 = new javax.swing.JLabel();
        lblexpecteddate1 = new javax.swing.JLabel();
        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        jScrollPane1.setOpaque(false);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.setOpaque(false);
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });
        txtquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtquantityFocusGained(evt);
            }
        });

        lblmaterialname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblmaterialname.setText("Material Name");

        lblquantiy.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblquantiy.setText("Quantity");

        lblexpecteddate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblexpecteddate.setText("Expected Date");

        txtmaterialname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaterialnameActionPerformed(evt);
            }
        });
        txtmaterialname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmaterialnameFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setText("ORDER DETAILS");

        btnmakeorder.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnmakeorder.setText("Make Order");
        btnmakeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmakeorderActionPerformed(evt);
            }
        });

        lblsupplieremail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblsupplieremail.setText("Supplier Email");

        lblsuppliername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblsuppliername.setText("Supplier Name");

        lblsuppliername1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblsuppliername1.setText("<empty>");

        lblsupplieremail1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblsupplieremail1.setText("<empty>");

        expecteddate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expecteddateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expecteddateFocusLost(evt);
            }
        });
        expecteddate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                expecteddatePropertyChange(evt);
            }
        });

        lblmaterialname1.setForeground(new java.awt.Color(255, 0, 0));

        lblquantity1.setForeground(new java.awt.Color(255, 0, 0));

        lblexpecteddate1.setForeground(new java.awt.Color(255, 0, 0));
        lblexpecteddate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblexpecteddate1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblquantiy)
                            .addComponent(lblexpecteddate)
                            .addComponent(lblmaterialname)
                            .addComponent(lblsupplieremail)
                            .addComponent(lblsuppliername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmaterialname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsupplieremail1)
                            .addComponent(lblsuppliername1)
                            .addComponent(lblmaterialname1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblquantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblexpecteddate1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expecteddate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnmakeorder)
                                .addGap(155, 155, 155)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsuppliername)
                            .addComponent(lblsuppliername1))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsupplieremail)
                            .addComponent(lblsupplieremail1))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmaterialname)
                            .addComponent(txtmaterialname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblmaterialname1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblquantiy)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblquantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblexpecteddate)
                            .addComponent(expecteddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(lblexpecteddate1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmakeorder)
                        .addGap(29, 29, 29))))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950, 450));

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        loadTable(txtSearch.getText());
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked

        int row = tblSupplier.getSelectedRow();

        lblsuppliername1.setText(tblSupplier.getValueAt(row, 1).toString());
        lblsupplieremail1.setText(tblSupplier.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtmaterialnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaterialnameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtmaterialnameActionPerformed

    private void btnmakeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmakeorderActionPerformed

        Cal cl = new Cal();
        boolean x = true;

        if (txtmaterialname.getText().isEmpty()) {
            lblmaterialname1.setText("*Please Enter Material Name Here");
            x = false;
        }

        if (txtquantity.getText().isEmpty()) {
            lblquantity1.setText("*Please Enter Quantity Here");
            x = false;
        }

        try {
            expecteddate.getDate().toString();
        }
        
        catch (NullPointerException e) {
            lblexpecteddate1.setText("*Please Select The Date Here");
            x = false;
        }

        try {
            int test = Integer.parseInt(txtquantity.getText().toString());
        }
        
        catch (NumberFormatException e) {
            lblquantity1.setText("*Please Enter A Number");
            x = false;
        }

        if (lblsuppliername1.getText().equals("<empty>") || lblsuppliername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            x = false;
        }

        if (x) {

            int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to send the e-mail");

            if (a == JOptionPane.YES_OPTION) {
                
                //EMAIL CODE HERE
                Mail m = new Mail();
                String msg;
                String adrs;

                adrs = lblsupplieremail1.getText().toString();
                msg = "Please deliver the material " + txtmaterialname.getText() + ", amount of " + txtquantity.getText() + " on or before " + expecteddate.getDate();

                m.sendMail(adrs, "Order Request", msg);
                
                lblsuppliername1.setText("<empty>");
                lblsupplieremail1.setText("<empty>");
                txtmaterialname.setText("");
                txtquantity.setText("");
                expecteddate.setDate(null);

               //EMAIL CODE HERE
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Failed to send the email");
            }

        }

    }//GEN-LAST:event_btnmakeorderActionPerformed

    private void txtmaterialnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmaterialnameFocusGained
        // TODO add your handling code here:
        lblmaterialname1.setText(null);
    }//GEN-LAST:event_txtmaterialnameFocusGained

    private void txtquantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquantityFocusGained
        // TODO add your handling code here:
        lblquantity1.setText(null);
    }//GEN-LAST:event_txtquantityFocusGained

    private void lblexpecteddate1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblexpecteddate1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblexpecteddate1FocusGained

    private void expecteddateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expecteddateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_expecteddateFocusGained

    private void expecteddateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expecteddateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_expecteddateFocusLost

    private void expecteddatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_expecteddatePropertyChange
        // TODO add your handling code here:
        lblexpecteddate1.setText(null);
    }//GEN-LAST:event_expecteddatePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnmakeorder;
    private com.toedter.calendar.JDateChooser expecteddate;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblexpecteddate;
    private javax.swing.JLabel lblexpecteddate1;
    private javax.swing.JLabel lblmaterialname;
    private javax.swing.JLabel lblmaterialname1;
    private javax.swing.JLabel lblquantity1;
    private javax.swing.JLabel lblquantiy;
    private javax.swing.JLabel lblsupplieremail;
    private javax.swing.JLabel lblsupplieremail1;
    private javax.swing.JLabel lblsuppliername;
    private javax.swing.JLabel lblsuppliername1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtmaterialname;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
