/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackage;

import data.OutletCustomer;
import DAO.OutletCustomerDAO;
import data.ReportView;
import java.awt.Color;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Dell
 */
public class OutletCustomerGUI extends javax.swing.JFrame {

    private Vector<Vector<String>> data;
    private Vector<String> header;

    /**
     * Creates new form OutletCustomer
     */
    int setfocusetab;

    public OutletCustomerGUI() {
        initComponents();

        OutletCustomerDAO stmt = new OutletCustomerDAO();

        header = new Vector<String>();
        header.add("Customer ID");
        header.add("First Name");
        header.add("Last Name");
        header.add("Address");
        header.add("Phone");
        header.add("Start Date");
        header.add("Email");
        loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);

       tplOutletCustomer.setBackground(new Color(0, 0, 0, 0));
    }

    private void loadtable(String no, JTable tb1, JScrollPane j1) {
        if (no.equals("Search...")) {
            no = "";
        }

        OutletCustomerDAO dao = new OutletCustomerDAO();
        data = dao.getoutletCustomerDetails(no);
        tblOutletCust.setModel(new javax.swing.table.DefaultTableModel(data, header));
        jScrollPane1.setViewportView(tblOutletCust);
    }

    private void clear() {
        txtFname.setText("");
        txtFname1.setText("");
        lblRFname.setText("");
        txtLname.setText("");
        txtLname1.setText("");
        lblRLname.setText("");
        txtAddress.setText("");
        txtAddress1.setText("");
        lblRAddr.setText("");
        txtPhone.setText("");
        txtPhone1.setText("");
        lblRPhone.setText("");
        txtEmail.setText("");
        txtEmail1.setText("");
        lblRemail.setText("");
        txtPhone.setText("");
        txtPhone1.setText("");
        lblRPhone.setText("");
        txtUPCusId.setText("");
        txtUpStartDate.setText("");
        lblRCUstID.setText("");
        lblRSdate.setText("");
        //txtSearch.setText("");
        lblUpEFname.setText("");
        lblUpELaname.setText("");
        lblUpEAddress.setText("");
        lblUpEPhone.setText("");
        lblUpEEmail.setText("");
        lblEfname.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutletCust = new javax.swing.JTable();
        tplOutletCustomer = new javax.swing.JTabbedPane();
        pnlAdd = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        lblEfname = new javax.swing.JLabel();
        lblELName = new javax.swing.JLabel();
        lblEAddress = new javax.swing.JLabel();
        lblEEmail = new javax.swing.JLabel();
        lblEPnone = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlUpadte = new javax.swing.JPanel();
        lblEmail1 = new javax.swing.JLabel();
        lblLname1 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        txtLname1 = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        txtFname1 = new javax.swing.JTextField();
        lblFname1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnUpClear = new javax.swing.JButton();
        lblUpEFname = new javax.swing.JLabel();
        lblUpELaname = new javax.swing.JLabel();
        lblUpEAddress = new javax.swing.JLabel();
        lblUpEPhone = new javax.swing.JLabel();
        lblUpEEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUPCusId = new javax.swing.JTextField();
        txtUpStartDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnlRemove = new javax.swing.JPanel();
        lblLname2 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        lblPhone2 = new javax.swing.JLabel();
        lblFname2 = new javax.swing.JLabel();
        lblCusId2 = new javax.swing.JLabel();
        btnremove = new javax.swing.JButton();
        btnReClear = new javax.swing.JButton();
        lblStartDate2 = new javax.swing.JLabel();
        lblRCUstID = new javax.swing.JLabel();
        lblRFname = new javax.swing.JLabel();
        lblRLname = new javax.swing.JLabel();
        lblRAddr = new javax.swing.JLabel();
        lblRPhone = new javax.swing.JLabel();
        lblRemail = new javax.swing.JLabel();
        lblRSdate = new javax.swing.JLabel();
        btnSelectCust = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnIreport = new javax.swing.JButton();
        txtiReport = new javax.swing.JTextField();
        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblReEFname = new javax.swing.JLabel();
        lblReECusId = new javax.swing.JLabel();
        lblReELname = new javax.swing.JLabel();
        lblReEAddress = new javax.swing.JLabel();
        lblReEPhone = new javax.swing.JLabel();
        lblReEEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusGained(evt);
            }
        });

        tblOutletCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOutletCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOutletCustMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOutletCust);

        tplOutletCustomer.setMaximumSize(new java.awt.Dimension(5000, 5000));

        pnlAdd.setMaximumSize(new java.awt.Dimension(5000, 5000));
        pnlAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlAddFocusGained(evt);
            }
        });

        lblEmail.setText("Email");

        lblLname.setText("Last Name");

        lblFname.setText("First Name");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(950, 650));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });

        lblPhone.setText("Phone No");

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        lblAddress.setText("Address");

        txtLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLnameFocusLost(evt);
            }
        });

        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnameFocusLost(evt);
            }
        });

        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddLayout = new javax.swing.GroupLayout(pnlAdd);
        pnlAdd.setLayout(pnlAddLayout);
        pnlAddLayout.setHorizontalGroup(
            pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFname)
                            .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAddress)
                                .addComponent(lblLname)
                                .addComponent(lblPhone)
                                .addComponent(lblEmail)))
                        .addGap(21, 21, 21)
                        .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblEEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblEPnone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                            .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblELName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEfname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(txtFname, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(pnlAddLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)
                        .addGap(791, 791, 791)
                        .addComponent(btnClear))
                    .addGroup(pnlAddLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddLayout.setVerticalGroup(
            pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblEfname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblELName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEPnone, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnClear)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))))
        );

        tplOutletCustomer.addTab("Add", pnlAdd);

        pnlUpadte.setMaximumSize(new java.awt.Dimension(5000, 5000));
        pnlUpadte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUpadteMouseClicked(evt);
            }
        });

        lblEmail1.setText("Email");

        lblLname1.setText("Last Name");

        txtLname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLname1FocusGained(evt);
            }
        });

        lblAddress1.setText("Address");

        lblPhone1.setText("Phone No");

        txtFname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFname1FocusGained(evt);
            }
        });
        txtFname1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtFname1InputMethodTextChanged(evt);
            }
        });
        txtFname1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFname1PropertyChange(evt);
            }
        });
        txtFname1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtFname1VetoableChange(evt);
            }
        });

        lblFname1.setText("First Name");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnUpClear.setText("Clear");
        btnUpClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpClearActionPerformed(evt);
            }
        });

        jLabel1.setText("CustomerID");

        jLabel2.setText("Start Date");

        txtUPCusId.setPreferredSize(new java.awt.Dimension(5, 20));
        txtUPCusId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUPCusIdActionPerformed(evt);
            }
        });

        jLabel4.setText("   ");

        javax.swing.GroupLayout pnlUpadteLayout = new javax.swing.GroupLayout(pnlUpadte);
        pnlUpadte.setLayout(pnlUpadteLayout);
        pnlUpadteLayout.setHorizontalGroup(
            pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpadteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress1)
                    .addComponent(lblEmail1)
                    .addComponent(lblPhone1)
                    .addComponent(jLabel1)
                    .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLname1)
                        .addComponent(lblFname1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpEFname, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUPCusId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFname1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(lblUpELaname, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpEPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpadteLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnUpClear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pnlUpadteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, lblUpEAddress, lblUpEEmail, lblUpEFname, lblUpELaname, lblUpEPhone, txtAddress1, txtEmail1, txtFname1, txtLname1, txtPhone1, txtUPCusId, txtUpStartDate});

        pnlUpadteLayout.setVerticalGroup(
            pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpadteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUPCusId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lblUpEFname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFname1)
                    .addComponent(txtFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lblUpELaname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLname1))
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addComponent(lblUpEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress1))
                .addGap(0, 0, 0)
                .addComponent(lblUpEPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone1))
                .addGap(0, 0, 0)
                .addComponent(lblUpEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail1)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUpadteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpClear)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tplOutletCustomer.addTab("Update", pnlUpadte);

        lblLname2.setText("Last Name");

        lblEmail2.setText("Email");

        lblAddress2.setText("Address");

        lblPhone2.setText("Phone No");

        lblFname2.setText("First Name");

        lblCusId2.setText("Customer ID");

        btnremove.setText("Remove");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        btnReClear.setText("Clear");
        btnReClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReClearActionPerformed(evt);
            }
        });

        lblStartDate2.setText("StartDate");

        lblRCUstID.setText(" ");

        lblRFname.setText(" ");

        lblRLname.setText(" ");

        lblRAddr.setText(" ");

        lblRPhone.setText(" ");

        lblRemail.setText(" ");

        lblRSdate.setText(" ");

        javax.swing.GroupLayout pnlRemoveLayout = new javax.swing.GroupLayout(pnlRemove);
        pnlRemove.setLayout(pnlRemoveLayout);
        pnlRemoveLayout.setHorizontalGroup(
            pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveLayout.createSequentialGroup()
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnremove)
                        .addGap(39, 39, 39)
                        .addComponent(btnReClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRemoveLayout.createSequentialGroup()
                                .addComponent(lblCusId2)
                                .addGap(27, 27, 27))
                            .addGroup(pnlRemoveLayout.createSequentialGroup()
                                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFname2)
                                    .addComponent(lblLname2)
                                    .addComponent(lblAddress2)
                                    .addComponent(lblEmail2)
                                    .addComponent(lblPhone2)
                                    .addComponent(lblStartDate2))
                                .addGap(36, 36, 36)))
                        .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblRLname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRFname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRCUstID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRemail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRSdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pnlRemoveLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRAddr, lblRCUstID, lblRFname, lblRLname, lblRPhone, lblRSdate, lblRemail});

        pnlRemoveLayout.setVerticalGroup(
            pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRCUstID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCusId2))
                .addGap(6, 6, 6)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRFname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFname2))
                .addGap(8, 8, 8)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRLname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLname2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress2))
                .addGap(11, 11, 11)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone2))
                .addGap(11, 11, 11)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRSdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartDate2))
                .addGap(73, 73, 73)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnremove)
                    .addComponent(btnReClear))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pnlRemoveLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblRAddr, lblRCUstID, lblRFname, lblRLname, lblRPhone, lblRSdate, lblRemail});

        tplOutletCustomer.addTab("Remove", pnlRemove);

        btnSelectCust.setText("Select Customer");
        btnSelectCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCustActionPerformed(evt);
            }
        });

        txtSearch.setText("Search...");
        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnIreport.setText("iReport");
        btnIreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIreportActionPerformed(evt);
            }
        });

        txtiReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplOutletCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectCust, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtiReport, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnIreport))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIreport)
                            .addComponent(txtiReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectCust, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tplOutletCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 950, 440));

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(lblReEFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 170, 21));
        getContentPane().add(lblReECusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 170, 19));
        getContentPane().add(lblReELname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 170, 24));
        getContentPane().add(lblReEAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -20, 44, 24));
        getContentPane().add(lblReEPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 44, 26));
        getContentPane().add(lblReEEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 44, 23));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        // TODO add your handling code here:
        tplOutletCustomer.setSelectedIndex(setfocusetab);
        txtFname.setForeground(Color.GRAY);
        txtFname.setText("First Name");
        txtLname.setForeground(Color.GRAY);
        txtLname.setText("Last Name");
        txtAddress.setForeground(Color.GRAY);
        txtAddress.setText("Address");
        txtPhone.setForeground(Color.GRAY);
        txtPhone.setText("Phone Number");
        txtEmail.setForeground(Color.GRAY);
        txtEmail.setText("ABC@gmail.com");
        txtSearch.setForeground(Color.GRAY);
        txtSearch.setText("Search...");
        txtUPCusId.setEditable(false);
        txtUpStartDate.setEditable(false);
        loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);


               tplOutletCustomer.setBackground(new Color(0, 0, 0, 0));
    }//GEN-LAST:event_formWindowOpened

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        boolean b1 = true, a = false;

        String fname = txtFname1.getText();
        if (fname.equals("") || (!fname.matches("^[a-zA-Z. ]{1,}"))) {
            lblUpEFname.setForeground(Color.red);
            lblUpEFname.setText(" Please Fild Text Feild!");
            b1 = false;
        }

        String lname = txtLname1.getText();
        if (lname.equals("") || (!lname.matches("^[a-zA-Z. ]{1,}"))) {
            lblUpELaname.setForeground(Color.red);
            lblUpELaname.setText("Please Fild Text Feild!");
            b1 = false;
        }
        String address = txtAddress1.getText();
        if (address.equals("")) {
            lblUpEAddress.setForeground(Color.red);
            lblUpEAddress.setText("Please Fild Text Feild!");
            b1 = false;
        }
        String email = txtEmail1.getText();
        if (email.equals("") || (email == null || email.indexOf("@") < 0 || email.indexOf(".") < 0 || email.indexOf(".") > email.length())) {
            lblUpEEmail.setForeground(Color.red);
            lblUpEEmail.setText("Please Fild valid Email!");
            b1 = false;
        }
        boolean isdigit = true;
        String phone = txtPhone1.getText();

        for (int i = 0; i < phone.length(); i++) {
            if (!Character.isDigit(phone.charAt(i))) {
                isdigit = false;
               
            }

        }
        if (!isdigit) {

            lblUpEPhone.setForeground(Color.red);
            lblUpEPhone.setText("Please Enter Numbers!");
            b1 = false;
        } else if (phone.length() != 10) {

            lblUpEPhone.setForeground(Color.red);
            lblUpEPhone.setText("Please Enter 10 Numbers!");
            b1 = false;
        }

        OutletCustomer u = new OutletCustomer();

        if (b1) {

            u.setFname(txtFname1.getText());
            u.setLname(txtLname1.getText());
            u.setAddress(txtAddress1.getText());
            u.setEmail(txtEmail1.getText());
            u.setPhone(txtPhone1.getText());
            u.setCusId(Integer.parseInt(txtUPCusId.getText()));
            u.setStartDate(txtUpStartDate.getText());
            OutletCustomerDAO dao2 = new OutletCustomerDAO();
            a = dao2.updateOutletCustomer(u);
            clear();
            loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
            if (a) {
                JOptionPane.showMessageDialog(null, "Customer Details Updated Successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Customer Details Update Faild!");
            }

        }

        //loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpClearActionPerformed
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpClearActionPerformed

    private void txtUPCusIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUPCusIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUPCusIdActionPerformed

    private void pnlUpadteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpadteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlUpadteMouseClicked

    private void tblOutletCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOutletCustMouseClicked

        if (tplOutletCustomer.getSelectedIndex() == 1) {
            int r = tblOutletCust.getSelectedRow();
            //OutletCustomerDAO dao1 = new OutletCustomerDAO();
            //data = dao5.getoutletCustomerDetails(string no);
            txtFname1.setText(tblOutletCust.getValueAt(r, 1).toString());
            txtLname1.setText(tblOutletCust.getValueAt(r, 2).toString());
            txtAddress1.setText(tblOutletCust.getValueAt(r, 3).toString());
            txtPhone1.setText(tblOutletCust.getValueAt(r, 4).toString());
            txtEmail1.setText(tblOutletCust.getValueAt(r, 6).toString());
            txtUPCusId.setText(tblOutletCust.getValueAt(r, 0).toString());

            try {
                txtUpStartDate.setText(tblOutletCust.getValueAt(r, 5).toString());
            } catch (NullPointerException ex) {
            }
            lblUpEFname.setText("");
            lblUpELaname.setText("");
            lblUpEAddress.setText("");
            lblUpEEmail.setText("");
            lblUpEPhone.setText("");

        }

        if (tplOutletCustomer.getSelectedIndex() == 2) {
            int r = tblOutletCust.getSelectedRow();
            lblRFname.setText(tblOutletCust.getValueAt(r, 1).toString());
            lblRLname.setText(tblOutletCust.getValueAt(r, 2).toString());
            lblRAddr.setText(tblOutletCust.getValueAt(r, 3).toString());
            lblRPhone.setText(tblOutletCust.getValueAt(r, 4).toString());
            lblRemail.setText(tblOutletCust.getValueAt(r, 6).toString());
            lblRCUstID.setText(tblOutletCust.getValueAt(r, 0).toString());
            try {
                lblRSdate.setText(tblOutletCust.getValueAt(r, 5).toString());
            } catch (NullPointerException ex) {
            }
            lblReEFname.setText("");
            lblReELname.setText("");
            lblReEAddress.setText("");
            lblReEEmail.setText("");
            lblReEPhone.setText("");

        }

// TODO add your handling code here:
    }//GEN-LAST:event_tblOutletCustMouseClicked

    private void txtFname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFname1FocusGained

    }//GEN-LAST:event_txtFname1FocusGained

    private void txtFname1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFname1PropertyChange

// TODO add your handling code here:
    }//GEN-LAST:event_txtFname1PropertyChange

    private void txtFname1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtFname1InputMethodTextChanged

    }//GEN-LAST:event_txtFname1InputMethodTextChanged

    private void txtFname1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtFname1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname1VetoableChange

    private void txtLname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLname1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLname1FocusGained

    private void btnSelectCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCustActionPerformed

        Outlet ot = new Outlet();
        int r = tblOutletCust.getSelectedRow();
        if (r >= 0) {
            String sc = tblOutletCust.getValueAt(r, 1).toString();
            ot.lblScus.setText(sc);
            ot.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a customer!");
        }
    }//GEN-LAST:event_btnSelectCustActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jScrollPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1FocusGained

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.setForeground(Color.BLACK);
        txtSearch.setText("");
        //txtSearch.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        boolean del = false;
        boolean b2 = true, ab = false;

        OutletCustomer u = new OutletCustomer();
        if (b2) {
            u.setFname(lblRFname.getText());
            u.setLname(lblRLname.getText());
            u.setAddress(lblRAddr.getText());
            u.setEmail(lblRemail.getText());
            u.setPhone(lblRPhone.getText());
            try {
                u.setCusId(Integer.parseInt(lblRCUstID.getText()));
            } catch (NumberFormatException ex) {
                System.out.println();

            }
            u.setStartDate(lblRSdate.getText());

            OutletCustomerDAO dao3 = new OutletCustomerDAO();
            int r = tblOutletCust.getSelectedRow();
            if (r >= 0) {
                int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this customer!");
                if (a == JOptionPane.YES_OPTION) {
                    String cid = tblOutletCust.getValueAt(r, 0).toString();
                    ab = dao3.deleteOutletCustomer(cid);
                    loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
                    clear();
                    loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
                    JOptionPane.showMessageDialog(null, "Customer Details Deleted Successfully !");

                }

                if (a == JOptionPane.NO_OPTION) {
                    clear();
                    txtSearch.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select a Customer!");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnremoveActionPerformed

    private void pnlAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlAddFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAddFocusGained

    private void txtFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusLost

        if (txtFname.getText().equals("")) {
            txtFname.setForeground(Color.GRAY);
            txtFname.setText("First Name");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameFocusLost

    private void txtFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusGained

        if (txtFname.getText().equals("First Name")) {

            txtFname.setForeground(Color.BLACK);
            txtFname.setText("");
            lblEfname.setText("");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txtFnameFocusGained

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost

        if (txtAddress.getText().equals("")) {
            txtAddress.setForeground(Color.GRAY);
            txtAddress.setText("Address");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained

        if (txtAddress.getText().equals("Address")) {
            txtAddress.setForeground(Color.BLACK);
            txtAddress.setText("");
            lblEAddress.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusLost
        if (txtLname.getText().equals("")) {
            txtLname.setForeground(Color.GRAY);
            txtLname.setText("Last Name");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameFocusLost

    private void txtLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusGained

        if (txtLname.getText().equals("Last Name")) {
            txtLname.setForeground(Color.BLACK);
            txtLname.setText("");
            lblELName.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

        if (txtEmail.getText().equals("")) {
            txtEmail.setForeground(Color.GRAY);
            txtEmail.setText("ABC@gmail.com");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained

        if (txtEmail.getText().equals("ABC@gmail.com")) {
            txtEmail.setForeground(Color.BLACK);
            txtEmail.setText("");
            lblEEmail.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost

        if (txtPhone.getText().equals("")) {
            txtPhone.setForeground(Color.GRAY);
            txtPhone.setText("Phone Number");
        }
        //// TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained

        if (txtPhone.getText().equals("Phone Number")) {
            txtPhone.setForeground(Color.BLACK);
            txtPhone.setText("");
            lblEPnone.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneFocusGained

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        // TODO add your handling code here:
        boolean e = true, abc = false;
        String fname = txtFname.getText();
        if (fname.equals("") || fname.equals("First Name") || (!fname.matches("^[a-zA-Z. ]{1,}"))) {
            e = false;
            lblEfname.setForeground(Color.red);
            lblEfname.setText("Please Enter your First Name!");
        }
        String lname = txtLname.getText();
        if (lname.equals("") || lname.equals("Last Name") || (!lname.matches("^[a-zA-Z. ]{1,}"))) {
            e = false;
            lblELName.setForeground(Color.red);
            lblELName.setText("Please Enter your Last Name!");
        }
        String address = txtAddress.getText();
        if (address.equals("") || address.equals("Address")) {
            e = false;
            lblEAddress.setForeground(Color.red);
            lblEAddress.setText("Please Enter your Address!");
        }
        boolean isdigit = true;
        String phone = txtPhone.getText();

        for (int i = 0; i < phone.length(); i++) {
            if (!Character.isDigit(phone.charAt(i))) {
                isdigit = false;
            }

        }
        if (!isdigit) {
            e = false;
            lblEPnone.setForeground(Color.red);
            lblEPnone.setText("Please Enter Numbers!");
        } else if (phone.length() != 10) {
            e = false;
            lblEPnone.setForeground(Color.red);
            lblEPnone.setText("Please Enter 10 Numbers!");
        }

        String email = txtEmail.getText();
        if ((email.equals("ABC@gmail.com")) || (email.indexOf("@") < 0 || email.indexOf(".") < 0 || email.indexOf(".") >= email.length())) {
            e = false;
            lblEEmail.setForeground(Color.red);
            lblEEmail.setText("Please Enter valid Email!");
        }

        if (e) {
            OutletCustomer o = new OutletCustomer(fname, lname, address, email, phone);

            //Save to the database
            OutletCustomerDAO dao1 = new OutletCustomerDAO();
            boolean a = dao1.addOutletCustomer(o);

            loadtable(txtSearch.getText(), tblOutletCust, jScrollPane1);
            if (a) {
                JOptionPane.showMessageDialog(null, "Customer Details Inserted Successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Customer Details Insert Faild!");
            }

            clear();

        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnReClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReClearActionPerformed
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReClearActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (txtSearch.getText().equals("")) {
            txtSearch.setForeground(Color.GRAY);
            txtSearch.setText("Search...");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtFname.setText("Sachi");
        txtLname.setText("Rathnayake");
        txtAddress.setText("Malabe");
        txtPhone.setText("0987654321");
        txtEmail.setText("abc@gmail.com");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIreportActionPerformed
        HashMap hm= new HashMap();
        hm.put("PARA_ADDRESS", txtiReport.getText());
        ReportView r = new ReportView("D:\\2nd yr2nd sem\\2014\\ITP\\sumisu\\Final\\JavaApplication9\\src\\Ireports\\OutletCustomerDetails.jasper",hm);
        r.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIreportActionPerformed

    private void txtiReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutletCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutletCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutletCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutletCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutletCustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIreport;
    private javax.swing.JButton btnReClear;
    private javax.swing.JButton btnSelectCust;
    private javax.swing.JButton btnUpClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblCusId2;
    private javax.swing.JLabel lblEAddress;
    private javax.swing.JLabel lblEEmail;
    private javax.swing.JLabel lblELName;
    private javax.swing.JLabel lblEPnone;
    private javax.swing.JLabel lblEfname;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblFname2;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblLname1;
    private javax.swing.JLabel lblLname2;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblRAddr;
    private javax.swing.JLabel lblRCUstID;
    private javax.swing.JLabel lblRFname;
    private javax.swing.JLabel lblRLname;
    private javax.swing.JLabel lblRPhone;
    private javax.swing.JLabel lblRSdate;
    private javax.swing.JLabel lblReEAddress;
    private javax.swing.JLabel lblReECusId;
    private javax.swing.JLabel lblReEEmail;
    private javax.swing.JLabel lblReEFname;
    private javax.swing.JLabel lblReELname;
    private javax.swing.JLabel lblReEPhone;
    private javax.swing.JLabel lblRemail;
    private javax.swing.JLabel lblStartDate2;
    private javax.swing.JLabel lblUpEAddress;
    private javax.swing.JLabel lblUpEEmail;
    private javax.swing.JLabel lblUpEFname;
    private javax.swing.JLabel lblUpELaname;
    private javax.swing.JLabel lblUpEPhone;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JPanel pnlRemove;
    private javax.swing.JPanel pnlUpadte;
    private javax.swing.JTable tblOutletCust;
    public static javax.swing.JTabbedPane tplOutletCustomer;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtFname1;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtLname1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUPCusId;
    private javax.swing.JTextField txtUpStartDate;
    private javax.swing.JTextField txtiReport;
    // End of variables declaration//GEN-END:variables
}
