/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackage;

import DAO.PayrollDAO;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import data.Cal;
import data.DBConnManager;
import data.PayrollDetails;
import data.ReportView;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.xml.soap.Text;

/**
 *
 * @author Dell
 */
public class Payroll extends javax.swing.JFrame {

    /**
     * Creates new form Payroll
     */
    private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header;//Used to store data header

    private Vector<Vector<String>> data2; //Used for data from database
    private Vector<String> header2;

    private Vector<Vector<String>> data1; //Used for data from database
    private Vector<String> header1; //Used to store data header

    public Payroll() {
        initComponents();

        jTabbedPane2.setBackground(new Color(0, 0, 0, 0));

        header = new Vector<String>();
        header.add("Employee ID");
        header.add("First Name");
        header.add("Last Name");
//        header.add("Allowance");

        header1 = new Vector<String>();
        header1.add("Employee ID");
        header1.add("First Name");
        header1.add("Basic Salary");
        header1.add("Allowance");
        header1.add("Bonus");

        header2 = new Vector<String>();
        header2.add("Employee ID");
        header2.add("Date");
        header2.add("Start Time");
        header2.add("End Time");
        test.hide();

//        loadTable(txtsearch.getText(),tbl1,jScrollPane2);
        loadTable(txtsearch.getText(), tblAttendance, jScrollPane1);
        Cal cl1 = new Cal();
        String dateattend = cl1.getDate();
        loadTable2(dateattend, tblAttendance1, jScrollPane3);
        System.out.println(dateattend);
        Cal c = new Cal();
            c.setDateTime(lbldate, lbltime);

    }

    private void loadTable(String no, JTable tbl, JScrollPane scp1) {

        PayrollDAO dao = new PayrollDAO();
        data = dao.getEmpDetails(no);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        scp1.setViewportView(tbl);
    }

    private void loadTable1(String no, JTable tbl, JScrollPane scp1) {

        PayrollDAO dao = new PayrollDAO();
        data1 = dao.getPayroll(no);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
                data1, header1));
        scp1.setViewportView(tbl);
    }

    private void loadTable2(String no, JTable tbl, JScrollPane scp1) {

        PayrollDAO dao = new PayrollDAO();
        data2 = dao.getAttendenceDetails(no);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
                data2, header2));
        scp1.setViewportView(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        empid = new javax.swing.JLabel();
        lblbasicsal = new javax.swing.JLabel();
        lblallowancess = new javax.swing.JLabel();
        txtamount1 = new javax.swing.JTextField();
        lbldeductions = new javax.swing.JLabel();
        txtamount2 = new javax.swing.JTextField();
        btnnetsalary = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtempid = new javax.swing.JTextField();
        txtbasicsal = new javax.swing.JTextField();
        lblvpempid = new javax.swing.JLabel();
        lblvbasicsal = new javax.swing.JLabel();
        lblvpallowances = new javax.swing.JLabel();
        lblvpbonus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        txtsearch2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        lblanswer = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblvempid = new javax.swing.JLabel();
        lblvdate = new javax.swing.JLabel();
        lblvattendtime = new javax.swing.JLabel();
        lblvleavetime = new javax.swing.JLabel();
        txtaempid = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        lblavempid = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAttendance1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldate.setFont(new java.awt.Font("LcdD", 0, 24)); // NOI18N
        lbldate.setText("date");
        jPanel4.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 110, -1));

        lbltime.setFont(new java.awt.Font("LcdD", 0, 24)); // NOI18N
        lbltime.setText("time");
        jPanel4.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 160, -1));

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        empid.setText("Emp ID");

        lblbasicsal.setText("Basic Sal");

        lblallowancess.setText("Allowances");

        txtamount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamount1ActionPerformed(evt);
            }
        });
        txtamount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtamount1KeyTyped(evt);
            }
        });

        lbldeductions.setText("Bonus");

        txtamount2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtamount2KeyTyped(evt);
            }
        });

        btnnetsalary.setText("Calc Net Salary");
        btnnetsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetsalaryActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        txtempid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtempidMouseClicked(evt);
            }
        });
        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });

        txtbasicsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbasicsalActionPerformed(evt);
            }
        });
        txtbasicsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbasicsalKeyTyped(evt);
            }
        });

        lblvpempid.setText(" ");

        lblvbasicsal.setText(" ");

        lblvpallowances.setText(" ");

        lblvpbonus.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbasicsal)
                            .addComponent(empid))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvbasicsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblvpempid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtempid, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtbasicsal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnetsalary))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblallowancess)
                            .addComponent(lbldeductions))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtamount2)
                            .addComponent(txtamount1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblvpallowances, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblvpbonus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empid)
                    .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblvpempid)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbasicsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbasicsal))
                .addGap(3, 3, 3)
                .addComponent(lblvbasicsal)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblallowancess)
                    .addComponent(txtamount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvpallowances, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeductions)
                    .addComponent(txtamount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblvpbonus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnnetsalary))
                .addGap(72, 72, 72))
        );

        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaymentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPayment);

        txtsearch2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch2KeyReleased(evt);
            }
        });

        jLabel3.setText("Search");

        test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select.jpg"))); // NOI18N

        lblanswer.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(test)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(test)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Payments", jPanel3);

        jLabel6.setText("Emp ID");

        jLabel7.setText("Date");

        lblvempid.setOpaque(true);

        lblvdate.setOpaque(true);

        lblvattendtime.setOpaque(true);

        txtaempid.setEditable(false);
        txtaempid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaempidFocusGained(evt);
            }
        });

        txtDate.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblvempid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblavempid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtaempid, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(txtDate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvattendtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblvleavetime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblvdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblvattendtime, lblvdate, lblvempid, lblvleavetime});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtaempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblvempid, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblavempid))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblvdate, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblvattendtime, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblvleavetime, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblvattendtime, lblvdate, lblvempid, lblvleavetime});

        btnADD.setText("In");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnOut.setText("Out");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAttendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAttendance);

        txtsearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsearchCaretUpdate(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        tblAttendance1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAttendance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAttendance1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblAttendance1);

        jLabel1.setText("Search Employee");

        jLabel2.setText("Attendance Table");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOut)
                            .addComponent(btnADD)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Attendance", jPanel7);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Basic Salary Reports");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Attendance Report");

        jButton2.setText("REPORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REPORT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2)))
                .addContainerGap(610, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(116, 116, 116)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton3))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reports", jPanel5);

        jPanel4.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 940, 450));

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 950, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        boolean chk1 = true;
        boolean b1 = false;

        if (txtempid.getText().equals("")) {
            lblvpempid.setForeground(Color.red);
            lblvpempid.setText("* Please Select Employee ID");
           // lblvbasicsal.setVisible(true);
            chk1 = false;
        }
        
        if (txtbasicsal.getText().equals("")) {
            lblvbasicsal.setForeground(Color.red);
            lblvbasicsal.setText("* Please Enter The Basic Salary");
            chk1 = false;
        }
        
        if (txtamount1.getText().equals("")) {
            lblvpallowances.setForeground(Color.red);
            lblvpallowances.setText("* Please Add Allowances ");
           chk1 = false;
       }
        
        
        
       if (txtamount2.getText().equals("")) {
            lblvpbonus.setForeground(Color.red);
            lblvpbonus.setText("* Please Add Bonus");
            chk1 = false;
        }

        if (chk1) {
            PayrollDAO dao1 = new PayrollDAO();
            PayrollDetails dData1 = new PayrollDetails();
            dData1.setBasicSal(Integer.parseInt(txtbasicsal.getText()));
            dData1.setAllowAmount(Integer.parseInt(txtamount1.getText()));
            dData1.setBonus(Integer.parseInt(txtamount2.getText()));
            dData1.setEmpID(Integer.parseInt(txtempid.getText()));
            b1 = dao1.updateEmployee(dData1);
        }
        if (b1) {
            loadTable1(txtsearch.getText(), tblPayment, jScrollPane2);
            JOptionPane.showMessageDialog(null, "Successfully Updated !");
            txtempid.setText("");
            txtbasicsal.setText("");
            txtamount1.setText("");
            txtamount2.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Update Failed !");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtamount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamount1ActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed

        Cal cl1 = new Cal();
        boolean chk = true;
        boolean b1 = false;
        String dateattend = cl1.getDate();
        loadTable2(dateattend, tblAttendance1, jScrollPane3);

        //validating
//            lblvdate.setForeground(Color.red);
//            lblvdate.setText(dateattend);
//            chk = false;
//        
//            String chek = txtatime.getText();
//            if(!chek.matches("-?\\d+(//.//d+)?")){
//            lblvattendtime.setText("Invalid time..");
//             chk = false;
//            }
//            
//            String chek1 = txtltime.getText();
//            if(!chek.matches("-?\\d+(//.//d+)?")){
//            lblvleavetime.setText("Invalid time..");
//             chk = false;
//            
// }             
        if (txtaempid.getText().equals("")) {
            lblavempid.setForeground(Color.red);
            lblavempid.setText("* Please Select Emp ID");
            chk = false;
        }
//        
//        if(!txtatime.getText().equals("")){    
//            
//            lblvattendtime.setText("* Please set attend time..");
//        }
//        
//        if(!txtltime.getText().equals("")){    
//        
//        
//                lblvleavetime.setText("* Please set leave time..");
//                txtltime.setText("");
//        }

        // TODO add your handling code here:
        if (chk) {
            PayrollDAO dao1 = new PayrollDAO();//creating DAO object
            PayrollDetails dData = new PayrollDetails();//creating DeliveryDetails object

            Cal c = new Cal();

            dData.setEmpID(Integer.parseInt(txtaempid.getText()));
            dData.setAttendtime(c.getTime());
            dData.setLeavetime(c.getTime());
            dData.setAdate(c.getDate());
            b1 = dao1.addAttendance(dData);
            if (b1) {
                loadTable(txtsearch.getText(), tblAttendance, jScrollPane1);
                loadTable2(dateattend, tblAttendance1, jScrollPane3);

                JOptionPane.showMessageDialog(null, "Attend time Successfully added");
                //AddClear();

            } else {
                JOptionPane.showMessageDialog(null, "Faild");
            }

        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void txtaempidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaempidFocusGained
        lblvempid.setText("");
    }//GEN-LAST:event_txtaempidFocusGained

    private void txtsearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsearchCaretUpdate
        loadTable(txtsearch.getText(), tblAttendance, jScrollPane1);
    }//GEN-LAST:event_txtsearchCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtempid.setEditable(false);
        txtempid.setEnabled(false);
//        loadTable(txtsearch.getText(),tbl1,jScrollPane2);
        loadTable(txtsearch.getText(), tblAttendance, jScrollPane1);

        loadTable1(txtsearch.getText(), tblPayment, jScrollPane2);

        Cal cl1 = new Cal();
        String dateattend = cl1.getDate();
        loadTable2(dateattend, tblAttendance1, jScrollPane3);

        Cal c = new Cal();
        txtDate.setText(c.getDate());

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed

        boolean chk = true;
        if (txtaempid.getText().equals("")) {
            lblavempid.setForeground(Color.red);
            lblavempid.setText("* Please Select Emp ID");
            chk = false;
        }
        if(chk)
        {
        Cal c = new Cal();
        String id = tblAttendance.getValueAt(tblAttendance.getSelectedRow(), 0).toString();
        String date = c.getDate();
        String time = c.getTime().toString();
        PayrollDetails pd = new PayrollDetails();
        pd.setEmpID(Integer.parseInt(id));
        pd.setAdate(date);
        pd.setLeavetime(time);
        PayrollDAO p = new PayrollDAO();
        boolean b = p.addAttendanceOut(pd);
        loadTable2("", tblAttendance1, jScrollPane3);

        }
//        loadTable2(id, tblPayment, jScrollPane1);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearch2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch2KeyReleased

        loadTable1(txtsearch2.getText(), tblPayment, jScrollPane2);

        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch2KeyReleased

    private void tblAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAttendanceMouseClicked

        int r = tblAttendance.getSelectedRow();
        String st = tblAttendance.getValueAt(r, 0).toString();
        txtaempid.setText(st);

        // TODO add your handling code here:
    }//GEN-LAST:event_tblAttendanceMouseClicked

    private void tblAttendance1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAttendance1MouseClicked
     
        int r = tblAttendance1.getSelectedRow();
        String st = tblAttendance1.getValueAt(r, 0).toString();
        txtaempid.setText(st);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAttendance1MouseClicked

    private void tblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaymentMouseClicked

        int r = tblPayment.getSelectedRow();
        String st = tblPayment.getValueAt(r, 0).toString();
        txtempid.setText(st);
        txtbasicsal.setText(tblPayment.getValueAt(r, 2).toString());
        txtamount1.setText(tblPayment.getValueAt(r, 3).toString());
        txtamount2.setText(tblPayment.getValueAt(r, 4).toString());
// TODO add your handling code here:
    }//GEN-LAST:event_tblPaymentMouseClicked

    private void txtbasicsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbasicsalActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbasicsalActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        if (jTabbedPane2.getSelectedIndex() == 0) {
            jTabbedPane2.setTitleAt(0, "*"+jTabbedPane2.getTitleAt(0));
          
        }
        if (jTabbedPane2.getSelectedIndex() == 1) {
           

        }
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void btnnetsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetsalaryActionPerformed

        int number1;
        int number2;
        int number3;
        int answer;
        lblanswer.setVisible(true);
        
        try {
            number1 = Integer.parseInt(this.txtbasicsal.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad Basic Salary", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            number2 = Integer.parseInt(this.txtamount1.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad Allowance", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            number3 = Integer.parseInt(this.txtamount2.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad Bonus", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
          answer = number1 + number2 + number3 ;
          this.lblanswer.setText("Net Salary  Is   :" +answer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnetsalaryActionPerformed

    private void txtbasicsalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbasicsalKeyTyped

        
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbasicsalKeyTyped

    private void txtamount1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamount1KeyTyped

        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamount1KeyTyped

    private void txtamount2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamount2KeyTyped

        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamount2KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HashMap hm= new HashMap();
//        hm.put("PARA_SA", txtreport.getText());
        ReportView r = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\salaryreport.jasper",hm);
        r.setVisible(true);
        
//        txtreport.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        HashMap hm= new HashMap();
//        hm.put("PARA_DATE", txtdatereport.getText());
        ReportView r = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\attendancereport.jasper",hm);
        r.setVisible(true);

//        txtdatereport.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtempidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtempidMouseClicked

        
         

    }//GEN-LAST:event_txtempidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnnetsalary;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel empid;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblallowancess;
    private javax.swing.JLabel lblanswer;
    private javax.swing.JLabel lblavempid;
    private javax.swing.JLabel lblbasicsal;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldeductions;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lblvattendtime;
    private javax.swing.JLabel lblvbasicsal;
    private javax.swing.JLabel lblvdate;
    private javax.swing.JLabel lblvempid;
    private javax.swing.JLabel lblvleavetime;
    private javax.swing.JLabel lblvpallowances;
    private javax.swing.JLabel lblvpbonus;
    private javax.swing.JLabel lblvpempid;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTable tblAttendance1;
    private javax.swing.JTable tblPayment;
    private javax.swing.JLabel test;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtaempid;
    private javax.swing.JTextField txtamount1;
    private javax.swing.JTextField txtamount2;
    private javax.swing.JTextField txtbasicsal;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsearch2;
    // End of variables declaration//GEN-END:variables
}
