/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appPackage;


import DAO.CustomerDAO;
import DAO.SupplierDAO;
import data.Cal;
import data.ReportView;
import data.SupplierDetails;
import java.awt.Color;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header; //Used to store data header
    
    public Supplier() {
        initComponents();
         header = new Vector<String>();
            header.add("Supplier ID");
            header.add("First Name");
            header.add("Last Name");
            header.add("Adress");
            header.add("Email");
            header.add("Phone");
            header.add("Account No");
            loadTable("");
               jTabbedPane1.setBackground(new Color(0, 0, 0, 0));

            
    }
    
    private void loadTable(String no){

        SupplierDAO dao = new SupplierDAO();
        data = dao.getSuppliertFiltered(no);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane1.setViewportView(tblSupplier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblFname = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAccounNo = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAccount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        lblEFname = new javax.swing.JLabel();
        lblELname = new javax.swing.JLabel();
        lblEAddress = new javax.swing.JLabel();
        lblEPhone = new javax.swing.JLabel();
        lblEEmail = new javax.swing.JLabel();
        lblEAccount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPhone1 = new javax.swing.JTextField();
        txtFname1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        lblFname1 = new javax.swing.JLabel();
        txtAccount1 = new javax.swing.JTextField();
        lblAccounNo1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblLname1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        txtLname1 = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        lblEFname1 = new javax.swing.JLabel();
        lblELname1 = new javax.swing.JLabel();
        lblEAddress1 = new javax.swing.JLabel();
        lblEPhone1 = new javax.swing.JLabel();
        lblEEmail1 = new javax.swing.JLabel();
        lblEAccount1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFname2 = new javax.swing.JLabel();
        lblLname2 = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        lblPhone2 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        lblAccounNo2 = new javax.swing.JLabel();
        lblFname3 = new javax.swing.JLabel();
        lblLname3 = new javax.swing.JLabel();
        lblAddress3 = new javax.swing.JLabel();
        lblPhone3 = new javax.swing.JLabel();
        lblEmail3 = new javax.swing.JLabel();
        lblAccounNo3 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        lblSupplierID2 = new javax.swing.JLabel();
        lblSupplierID3 = new javax.swing.JLabel();
        Report = new javax.swing.JPanel();
        btniReportcontact = new javax.swing.JButton();
        supContacts = new javax.swing.JLabel();
        supLocation = new javax.swing.JLabel();
        btnReportLocation = new javax.swing.JButton();
        supemail = new javax.swing.JLabel();
        btnReportEmail = new javax.swing.JButton();
        supfull = new javax.swing.JLabel();
        btnReportFull = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pnlBtn = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);

        lblFname.setText("First Name");

        lblLname.setText("Last Name");

        lblAddress.setText("Address");

        lblPhone.setText("Phone");

        lblEmail.setText("Email");

        lblAccounNo.setText("Account No");

        txtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnameFocusGained(evt);
            }
        });

        txtLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLnameFocusGained(evt);
            }
        });

        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
        });

        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });

        txtAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountActionPerformed(evt);
            }
        });
        txtAccount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAccountFocusGained(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        lblEFname.setForeground(new java.awt.Color(255, 0, 0));

        lblELname.setForeground(new java.awt.Color(255, 0, 0));

        lblEAddress.setForeground(new java.awt.Color(255, 0, 0));

        lblEPhone.setForeground(new java.awt.Color(255, 0, 0));

        lblEEmail.setForeground(new java.awt.Color(255, 0, 0));

        lblEAccount.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFname)
                            .addComponent(lblLname))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEFname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAccounNo)
                                    .addComponent(lblEmail))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress)
                                    .addComponent(lblPhone))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblELname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEFname, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblELname, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblEAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccounNo)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel1);

        txtPhone1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPhone1CaretUpdate(evt);
            }
        });
        txtPhone1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhone1FocusGained(evt);
            }
        });

        txtFname1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtFname1CaretUpdate(evt);
            }
        });
        txtFname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFname1FocusGained(evt);
            }
        });

        lblEmail1.setText("Email");

        txtAddress1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtAddress1CaretUpdate(evt);
            }
        });
        txtAddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddress1FocusGained(evt);
            }
        });

        txtEmail1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEmail1CaretUpdate(evt);
            }
        });
        txtEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmail1FocusGained(evt);
            }
        });

        lblFname1.setText("First Name");

        txtAccount1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtAccount1CaretUpdate(evt);
            }
        });
        txtAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccount1ActionPerformed(evt);
            }
        });
        txtAccount1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAccount1FocusGained(evt);
            }
        });

        lblAccounNo1.setText("Account No");

        lblAddress1.setText("Address");

        lblLname1.setText("Last Name");

        lblPhone1.setText("Phone");

        txtLname1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtLname1CaretUpdate(evt);
            }
        });
        txtLname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLname1FocusGained(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear2.setText("Clear");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });

        lblEFname1.setForeground(new java.awt.Color(255, 0, 0));

        lblELname1.setForeground(new java.awt.Color(255, 0, 0));

        lblEAddress1.setForeground(new java.awt.Color(255, 0, 0));

        lblEPhone1.setForeground(new java.awt.Color(255, 0, 0));

        lblEEmail1.setForeground(new java.awt.Color(255, 0, 0));

        lblEAccount1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress1)
                            .addComponent(lblPhone1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFname1)
                                    .addComponent(lblLname1))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblELname1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail1)
                                    .addComponent(lblAccounNo1))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname1)
                    .addComponent(txtFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblEFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname1)
                    .addComponent(txtLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblELname1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail1)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblEEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccounNo1)
                    .addComponent(txtAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update", jPanel2);

        lblFname2.setText("First Name");

        lblLname2.setText("Last Name");

        lblAddress2.setText("Address");

        lblPhone2.setText("Phone");

        lblEmail2.setText("Email");

        lblAccounNo2.setText("Account No");

        lblFname3.setText("First Name");

        lblLname3.setText("Last Name");

        lblAddress3.setText("Address");

        lblPhone3.setText("Phone");

        lblEmail3.setText("Email");

        lblAccounNo3.setText("Account No");

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblSupplierID2.setText("Supplier ID");

        lblSupplierID3.setText("Supplier ID");
        lblSupplierID3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblSupplierID3FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress2)
                    .addComponent(lblFname2)
                    .addComponent(lblLname2)
                    .addComponent(lblPhone2)
                    .addComponent(lblEmail2)
                    .addComponent(lblAccounNo2)
                    .addComponent(lblSupplierID2))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierID3)
                    .addComponent(btnRemove)
                    .addComponent(lblAccounNo3)
                    .addComponent(lblEmail3)
                    .addComponent(lblPhone3)
                    .addComponent(lblLname3)
                    .addComponent(lblFname3)
                    .addComponent(lblAddress3))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierID2)
                    .addComponent(lblSupplierID3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname2)
                    .addComponent(lblFname3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLname3)
                    .addComponent(lblLname2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress2)
                    .addComponent(lblAddress3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone2)
                    .addComponent(lblPhone3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail2)
                    .addComponent(lblEmail3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccounNo2)
                    .addComponent(lblAccounNo3))
                .addGap(50, 50, 50)
                .addComponent(btnRemove)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove", jPanel3);

        btniReportcontact.setText("iReport");
        btniReportcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniReportcontactActionPerformed(evt);
            }
        });

        supContacts.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        supContacts.setText("Supplier Contact Details");

        supLocation.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        supLocation.setText("Supplier Location Details");

        btnReportLocation.setLabel("iReport");
        btnReportLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportLocationActionPerformed(evt);
            }
        });

        supemail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        supemail.setText("Supplier Email Details");

        btnReportEmail.setLabel("iReport");
        btnReportEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportEmailActionPerformed(evt);
            }
        });

        supfull.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        supfull.setText("Supplier Full Details");

        btnReportFull.setText("iReport");
        btnReportFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report);
        Report.setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportLayout.createSequentialGroup()
                .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btniReportcontact))
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supfull, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnReportLocation))
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnReportEmail))
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnReportFull)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(supContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btniReportcontact)
                .addGap(20, 20, 20)
                .addComponent(supLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReportLocation)
                .addGap(20, 20, 20)
                .addComponent(supemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReportEmail)
                .addGap(20, 20, 20)
                .addComponent(supfull, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReportFull)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        btnReportLocation.getAccessibleContext().setAccessibleName("iReport");

        jTabbedPane1.addTab("Reports", Report);

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        jScrollPane1.setOpaque(false);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.setOpaque(false);
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950, 450));

        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, -1, -1));

        pnlBtn.setOpaque(false);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setOpaque(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setOpaque(false);
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fourcus_Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Focus_delete.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnLayout = new javax.swing.GroupLayout(pnlBtn);
        pnlBtn.setLayout(pnlBtnLayout);
        pnlBtnLayout.setHorizontalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        pnlBtnLayout.setVerticalGroup(
            pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnLayout.createSequentialGroup()
                .addGroup(pnlBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(logout)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainmenubackgroundWindows.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                     
        boolean b1,ac,bc,cc,dc,ec;
        
        ac = requieFieldValidation(1);
        bc = nameNoNumricValidation(1);
        cc = validatePhoneNumber(1);   
        dc = validateAccountNumber(1);
        ec = validateEmailAddress(1);
        
        if(ac && bc && cc && dc && ec)
        {
            SupplierDetails d = new SupplierDetails(Integer.parseInt(txtAccount.getText()), txtFname.getText(), txtLname.getText(), txtAddress.getText(), txtEmail.getText(), Integer.parseInt(txtPhone.getText()));
            SupplierDAO dao = new SupplierDAO();
            b1 = dao.addSupplier(d);
            if(b1)
            {
                JOptionPane.showMessageDialog(null, "Successfully Added ");
                loadTable("");
                txtFname.setText(null);
                txtLname.setText(null);
                txtAccount.setText(null);
                txtAddress.setText(null);
                txtEmail.setText(null);
                txtPhone.setText(null);
            }
            else
                JOptionPane.showMessageDialog(null, "Failed");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccount1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        txtFname.setText(null);
        txtLname.setText(null);
        txtAccount.setText(null);
        txtAddress.setText(null);
        txtEmail.setText(null);
        txtPhone.setText(null);
    }//GEN-LAST:event_btnClear1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        boolean b1,ac,bc,cc,dc,ec;;
        
        int row = tblSupplier.getSelectedRow();
        
        ac = requieFieldValidation(2);
        bc = nameNoNumricValidation(2);
        cc = validatePhoneNumber(2);   
        dc = validateAccountNumber(2);
        ec = validateEmailAddress(2);
        
        if(ac && bc && cc && dc && ec)
        {
            SupplierDetails d = new SupplierDetails(Integer.parseInt(txtAccount1.getText()), txtFname1.getText(), txtLname1.getText(), txtAddress1.getText(), txtEmail1.getText(), Integer.parseInt(txtPhone1.getText()));
            d.setSupId(Integer.parseInt(tblSupplier.getValueAt(row, 0).toString()));
            SupplierDAO dao = new SupplierDAO();
            b1 = dao.updateSupplier(d);
            if(b1)
            {
                JOptionPane.showMessageDialog(null, "Successfully Updated ");
                loadTable("");
                txtFname1.setText(null);
                txtLname1.setText(null);
                txtAccount1.setText(null);
                txtAddress1.setText(null);
                txtEmail1.setText(null);
                txtPhone1.setText(null);
            }
            else
                JOptionPane.showMessageDialog(null, "Failed");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        loadTable(txtSearch.getText());
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        int row = tblSupplier.getSelectedRow();
        
        
        if(jTabbedPane1.getSelectedIndex()==1)  
        {
            txtFname1.setText(tblSupplier.getValueAt(row, 1).toString());
            txtLname1.setText(tblSupplier.getValueAt(row, 2).toString());
            txtAddress1.setText(tblSupplier.getValueAt(row, 3).toString());
            txtPhone1.setText(tblSupplier.getValueAt(row, 5).toString());
            txtEmail1.setText(tblSupplier.getValueAt(row, 4).toString());
            txtAccount1.setText(tblSupplier.getValueAt(row, 6).toString());
        }
        
        if((jTabbedPane1.getSelectedIndex()==2))
        {
        
            lblSupplierID3.setText(tblSupplier.getValueAt(row, 0).toString());
            lblFname3.setText(tblSupplier.getValueAt(row, 1).toString());
            lblLname3.setText(tblSupplier.getValueAt(row, 2).toString());
            lblAddress3.setText(tblSupplier.getValueAt(row, 3).toString());
            lblPhone3.setText(tblSupplier.getValueAt(row, 5).toString());
            lblEmail3.setText(tblSupplier.getValueAt(row, 4).toString());
            lblAccounNo3.setText(tblSupplier.getValueAt(row, 6).toString());

        }
        
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void txtFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusGained
        lblEFname.setText(null);
    }//GEN-LAST:event_txtFnameFocusGained

    private void txtLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusGained
        lblELname.setText(null);
    }//GEN-LAST:event_txtLnameFocusGained

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        lblEAddress.setText(null);
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        lblEPhone.setText(null);
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        lblEEmail.setText(null);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtAccountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAccountFocusGained
        lblEAccount.setText(null);
    }//GEN-LAST:event_txtAccountFocusGained

    private void txtFname1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFname1CaretUpdate
        lblEFname1.setText(null);
    }//GEN-LAST:event_txtFname1CaretUpdate

    private void txtLname1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtLname1CaretUpdate
        lblELname1.setText(null);
    }//GEN-LAST:event_txtLname1CaretUpdate

    private void txtAddress1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAddress1CaretUpdate
        lblEAddress1.setText(null);
    }//GEN-LAST:event_txtAddress1CaretUpdate

    private void txtPhone1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPhone1CaretUpdate
        lblEPhone1.setText(null);
    }//GEN-LAST:event_txtPhone1CaretUpdate

    private void txtEmail1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEmail1CaretUpdate
        lblEEmail1.setText(null);
    }//GEN-LAST:event_txtEmail1CaretUpdate

    private void txtAccount1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAccount1CaretUpdate
        lblEAccount1.setText(null);
    }//GEN-LAST:event_txtAccount1CaretUpdate

    private void txtFname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFname1FocusGained
        lblEFname1.setText(null);
    }//GEN-LAST:event_txtFname1FocusGained

    private void txtLname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLname1FocusGained
        lblELname1.setText(null);
    }//GEN-LAST:event_txtLname1FocusGained

    private void txtAddress1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddress1FocusGained
        lblEAddress1.setText(null);
    }//GEN-LAST:event_txtAddress1FocusGained

    private void txtPhone1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhone1FocusGained
        lblEPhone1.setText(null);
    }//GEN-LAST:event_txtPhone1FocusGained

    private void txtEmail1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail1FocusGained
        lblEEmail1.setText(null);
    }//GEN-LAST:event_txtEmail1FocusGained

    private void txtAccount1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAccount1FocusGained
        lblEAccount1.setText(null);
    }//GEN-LAST:event_txtAccount1FocusGained

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        txtFname1.setText(null);
        txtLname1.setText(null);
        txtAccount1.setText(null);
        txtAddress1.setText(null);
        txtEmail1.setText(null);
        txtPhone1.setText(null);
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

            
            if(lblSupplierID3.getText().equals("") || lblSupplierID3.getText().equalsIgnoreCase("Supplier ID"))
            {
                JOptionPane.showMessageDialog(null, "Please select a row");
            }
            
            else
            {
            
                int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to remove");

                if(a==JOptionPane.YES_OPTION)
                {
                     boolean b123 = true;

                     SupplierDAO dao = new SupplierDAO();
                     int row = tblSupplier.getSelectedRow();
                     String supId = tblSupplier.getValueAt(row, 0).toString();

                     txtSearch.setText("");
                     loadTable(txtSearch.getText());

                     b123 = dao.removeSupplier(supId);
                     System.out.println(b123);
                     if(b123)
                     {
                         JOptionPane.showMessageDialog(null, "Successfully Removed ");
                         loadTable("");
                         lblSupplierID3.setText("");
                         lblFname3.setText("");
                         lblLname3.setText("");
                         lblAccounNo3.setText("");
                         lblAddress3.setText("");
                         lblEmail3.setText("");
                         lblPhone3.setText("");
                     }
                     else
                         JOptionPane.showMessageDialog(null, "Failed"); 
                }
        
            }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        MainMenu m = new MainMenu();
        m.b = true;
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        MainMenu m = new MainMenu();
        m.b = false;
        m.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a =JOptionPane.showConfirmDialog(rootPane, "Do you want to exit");
        if(a == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblSupplierID3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblSupplierID3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSupplierID3FocusGained

    private void btniReportcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniReportcontactActionPerformed
            HashMap hm = new HashMap();
            hm.put("PARA_SUP", btniReportcontact.getText());
            ReportView r = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\Supplier_Contact_Details.jasper");
            r.setVisible(true);
            
            //TODO add your handling code here:
    }//GEN-LAST:event_btniReportcontactActionPerformed

    private void btnReportLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportLocationActionPerformed
        // TODO add your handling code here:
        HashMap hm = new HashMap();
            hm.put("PARA_SUP", btniReportcontact.getText());
            ReportView r = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\Supplier_Location_Details.jasper");
            r.setVisible(true);
    }//GEN-LAST:event_btnReportLocationActionPerformed

    private void btnReportEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportEmailActionPerformed
        // TODO add your handling code here:
        HashMap hm = new HashMap();
        hm.put("PARA_SUP", btniReportcontact.getText());
        ReportView r = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\Supplier_Email_Details.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_btnReportEmailActionPerformed

    private void btnReportFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportFullActionPerformed
        // TODO add your handling code here:
        HashMap hm = new HashMap();
        hm.put("PARA_SUP", btniReportcontact.getText());
        ReportView r = new ReportView("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication9\\src\\iReport\\Supplier_Full_Details.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_btnReportFullActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtFname.setText("Saman");
        txtLname.setText("Rathnapala");
        txtAccount.setText("9867545");
        txtAddress.setText("Colombo");
        txtEmail.setText("abc@gmail.com ");
        txtPhone.setText("0987654321");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }
    
    boolean requieFieldValidation(int a){
        
        boolean x1=true;
        
        if(a==1)
        {
            if(txtAccount.getText().isEmpty()){

                lblEAccount.setText("*Please Enter The Account Number");
                x1=false;
            }
            if(txtAddress.getText().isEmpty())
            {
                lblEAddress.setText("*Please Enter The Address");
                x1=false;
            }
            if(txtEmail.getText().isEmpty())
            {
                lblEEmail.setText("*Please Enter The Email");
                x1=false;
            }
            if(txtFname.getText().isEmpty())
            {
                lblEFname.setText("*Please Enter The First Name");
                x1=false;
            }
            if(txtLname.getText().isEmpty())
            {
                lblELname.setText("*Please Enter The Last Name");
                x1=false;
            }
            if(txtPhone.getText().isEmpty())
            {
                lblEPhone.setText("*Please Enter The Phone Number");
                x1=false;
            }

        }
        
        if(a==2)
        {
            if(txtAccount1.getText().isEmpty()){

                lblEAccount1.setText("*Please Enter The Account Number");
                x1=false;
            }
            if(txtAddress1.getText().isEmpty())
            {
                lblEAddress1.setText("*Please Enter The Address");
                x1=false;
            }
            if(txtEmail1.getText().isEmpty())
            {
                lblEEmail1.setText("*Please Enter The Email");
                x1=false;
            }
            if(txtFname1.getText().isEmpty())
            {
                lblEFname1.setText("*Please Enter The First Name");
                x1=false;
            }
            if(txtLname1.getText().isEmpty())
            {
                lblELname1.setText("*Please Enter The Last Name");
                x1=false;
            }
            if(txtPhone1.getText().isEmpty())
            {
                lblEPhone1.setText("*Please Enter The Phone Number");
                x1=false;
            }
        }
        
        return x1;
    }
    
    boolean nameNoNumricValidation(int a){
        
        boolean x2=true;
        boolean isFnameDigit = false;
        boolean isLnameDigit = false;
        
        if(a==1)
        {
            char arr[] = new char[txtFname.getText().length()];
            arr = txtFname.getText().toCharArray();
            for(char d: arr)
                if(Character.isDigit(d))
                    isFnameDigit = true;

            char arr2[] = new char[txtLname.getText().length()];
            arr2 = txtLname.getText().toCharArray();
            for(char d: arr2)
                if(Character.isDigit(d))
                    isLnameDigit = true;

            if(isFnameDigit){
                lblEFname.setText("Invalid First Name");
                x2=false;
            }
            else if(isLnameDigit){
                lblELname.setText("Invalid Last Name");
                x2=false;
            }
        }
        if(a==2)
        {
            char arr[] = new char[txtFname1.getText().length()];
            arr = txtFname1.getText().toCharArray();
            for(char d: arr)
                if(Character.isDigit(d))
                    isFnameDigit = true;

            char arr2[] = new char[txtLname1.getText().length()];
            arr2 = txtLname1.getText().toCharArray();
            for(char d: arr2)
                if(Character.isDigit(d))
                    isLnameDigit = true;

            if(isFnameDigit){
                lblEFname1.setText("Invalid First Name");
                x2=false;
            }
            else if(isLnameDigit){
                lblELname1.setText("Invalid Last Name");
                x2=false;
            }
        }
        
        return x2;
    }
    
    boolean validatePhoneNumber(int a){
        
        boolean  x3=true;
        
        if(a==1)
        {
            try{
               int test = Integer.parseInt(txtPhone.getText().toString());
            }
            catch(NumberFormatException e){
                lblEPhone.setText("*Invalid Phone Number");
                x3=false;
            }
            
            if(txtPhone.getText().length()!=10)
            {
                lblEPhone.setText("*Please Enter 10 Digits");
                x3=false;
            }
        }
        if (a==2)
        {
           try{
              int test = Integer.parseInt(txtPhone1.getText().toString());
           }
           catch(NumberFormatException e){
               lblEPhone1.setText("*Invalid Phone Number");
               x3=false;
           }
           
           if(txtPhone1.getText().length()!=10)
            {
                lblEPhone1.setText("*Please Enter 10 Digits");
                x3=false;
            }
        }
        return x3;
    }
    
    boolean validateAccountNumber(int a){
        
        boolean x4=true;
        boolean isNotValidated = false;
        
        if(a==1)
        {
            char arr[] = new char[txtAccount.getText().length()];
            arr = txtAccount.getText().toCharArray();
            for(char d: arr)
                if(!Character.isDigit(d) && d != '-')
                    isNotValidated = true;

            if(isNotValidated){
                lblEAccount.setText("*Invalid Account Number");
                x4=false;
            }
        }
        if(a==2)
        {
            char arr[] = new char[txtAccount1.getText().length()];
            arr = txtAccount1.getText().toCharArray();
            for(char d: arr)
                if(!Character.isDigit(d) && d != '-')
                    isNotValidated = true;

            if(isNotValidated){
                lblEAccount1.setText("*Invalid Account Number");
                x4=false;
            }
        }
        return x4;
    }
    
    boolean validateEmailAddress(int a){
        
        boolean x5=true;
        
        if(a==1)
        {
            int dotIndex = txtEmail.getText().indexOf('.');
            int AtIndex = txtEmail.getText().indexOf('@');

            boolean isNotValidated = false;

            if(dotIndex == -1 || AtIndex == -1)
                isNotValidated =true;

            if(isNotValidated){
                lblEEmail.setText("*Invalid Email");
                x5=false;
            }
        }
        
        if(a==2)
        {
            int dotIndex = txtEmail1.getText().indexOf('.');
            int AtIndex = txtEmail1.getText().indexOf('@');

            boolean isNotValidated = false;

            if(dotIndex == -1 || AtIndex == -1)
                isNotValidated =true;

            if(isNotValidated){
                lblEEmail1.setText("*Invalid Email");
                x5=false;
            }
        }
        
        return x5;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Report;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReportEmail;
    private javax.swing.JButton btnReportFull;
    private javax.swing.JButton btnReportLocation;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btniReportcontact;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAccounNo;
    private javax.swing.JLabel lblAccounNo1;
    private javax.swing.JLabel lblAccounNo2;
    private javax.swing.JLabel lblAccounNo3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAddress3;
    private javax.swing.JLabel lblEAccount;
    private javax.swing.JLabel lblEAccount1;
    private javax.swing.JLabel lblEAddress;
    private javax.swing.JLabel lblEAddress1;
    private javax.swing.JLabel lblEEmail;
    private javax.swing.JLabel lblEEmail1;
    private javax.swing.JLabel lblEFname;
    private javax.swing.JLabel lblEFname1;
    private javax.swing.JLabel lblELname;
    private javax.swing.JLabel lblELname1;
    private javax.swing.JLabel lblEPhone;
    private javax.swing.JLabel lblEPhone1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblFname2;
    private javax.swing.JLabel lblFname3;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblLname1;
    private javax.swing.JLabel lblLname2;
    private javax.swing.JLabel lblLname3;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblPhone3;
    private javax.swing.JLabel lblSupplierID2;
    private javax.swing.JLabel lblSupplierID3;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JLabel supContacts;
    private javax.swing.JLabel supLocation;
    private javax.swing.JLabel supemail;
    private javax.swing.JLabel supfull;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAccount1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtFname1;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtLname1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
